import { StyleSheet, Platform } from 'react-native'
import { fonts } from '../../../constant'
import { wp, hp, normalizeStyleOptions, screenPadding, getContentMaxWidth } from '../../../theme/layout'
import { cardShadow } from '../../../theme/shadows'

export default function getStyles(colors, isDark = false, options = {}) {
  const { isCompact = false, isWide = false } = normalizeStyleOptions(options)
  const padH = screenPadding(isWide, isCompact)
  const contentMaxWidth = getContentMaxWidth(isWide)
  const borderColor = colors.surfaceBorder || colors.border
  const cardBg = isDark ? colors.cardBg : colors.white || colors.cardBg
  const upcomingBg = isDark ? 'rgba(16, 185, 129, 0.18)' : '#ECFDF5'
  const upcomingBorder = isDark ? 'rgba(16, 185, 129, 0.35)' : '#A7F3D0'
  const pastBg = isDark ? 'rgba(59, 130, 246, 0.12)' : '#F8FAFC'
  const pastBorder = isDark ? 'rgba(59, 130, 246, 0.25)' : '#E2E8F0'
  const cancelledBg = isDark ? 'rgba(148, 163, 184, 0.14)' : '#F1F5F9'
  const cancelledBorder = isDark ? 'rgba(148, 163, 184, 0.3)' : '#E2E8F0'
  const panelShadow = cardShadow(isDark, 'soft')

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.appBg || colors.dark,
    },
    scrollContent: {
      paddingHorizontal: padH,
      paddingBottom: hp(4),
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: isWide ? 'center' : 'stretch',
    },
    summaryCard: {
      borderRadius: 18,
      padding: wp(4),
      marginTop: hp(1),
      marginBottom: hp(1.6),
      backgroundColor: cardBg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      ...panelShadow,
    },
    summaryTop: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: wp(3.5),
      marginBottom: hp(1.6),
    },
    summaryIconWrap: {
      width: 46,
      height: 46,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    summaryTextWrap: {
      flex: 1,
    },
    summaryTitle: {
      fontSize: 18,
      fontFamily: fonts.bold,
      color: colors.text,
      letterSpacing: 0.2,
    },
    summarySubtitle: {
      marginTop: 3,
      fontSize: 13,
      fontFamily: fonts.regular,
      color: colors.gray,
      lineHeight: 18,
    },
    summaryStats: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingTop: hp(1.4),
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: borderColor,
    },
    statChip: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: hp(0.8),
      borderRadius: 12,
    },
    statValue: {
      fontSize: 20,
      fontFamily: fonts.bold,
      color: colors.text,
    },
    statLabel: {
      marginTop: 2,
      fontSize: 11,
      fontFamily: fonts.medium,
      color: colors.gray,
      letterSpacing: 0.4,
    },
    statDivider: {
      width: StyleSheet.hairlineWidth,
      height: 36,
      backgroundColor: borderColor,
      marginHorizontal: wp(2),
    },
    legendRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      flexWrap: 'wrap',
    },
    legendItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 20,
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : colors.inputBg,
    },
    legendDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    legendText: {
      fontSize: 11,
      fontFamily: fonts.medium,
      color: colors.gray,
    },
    controlsCard: {
      backgroundColor: cardBg,
      borderRadius: 18,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      padding: wp(3.5),
      marginBottom: hp(1.6),
      ...panelShadow,
    },
    navRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: hp(1.2),
    },
    navButton: {
      width: 36,
      height: 36,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : colors.inputBg,
    },
    todayButton: {
      height: 36,
      paddingHorizontal: 14,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: `${colors.primary}14`,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: `${colors.primary}33`,
    },
    todayButtonText: {
      fontSize: 13,
      fontFamily: fonts.semibold,
      color: colors.primary,
    },
    rangeTitle: {
      flex: 1,
      minWidth: 120,
      fontSize: 16,
      fontFamily: fonts.bold,
      color: colors.text,
      textAlign: 'center',
      letterSpacing: 0.2,
    },
    segmentedRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : colors.inputBg,
      padding: 4,
      flex: 1,
      minWidth: 180,
    },
    segmentedOption: {
      flex: 1,
      paddingVertical: 8,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
    },
    segmentedOptionActive: {
      backgroundColor: colors.primary,
      ...Platform.select({
        ios: {
          shadowColor: colors.primary,
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.25,
          shadowRadius: 4,
        },
        android: { elevation: 2 },
      }),
    },
    segmentedText: {
      fontSize: 12,
      fontFamily: fonts.medium,
      color: colors.gray,
    },
    segmentedTextActive: {
      color: colors.white,
      fontFamily: fonts.semibold,
    },
    statusRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : colors.inputBg,
      padding: 4,
    },
    statusOption: {
      flex: 1,
      paddingVertical: 9,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statusOptionActive: {
      backgroundColor: cardBg,
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: isDark ? 0.2 : 0.08,
          shadowRadius: 3,
        },
        android: { elevation: 1 },
      }),
    },
    statusText: {
      fontSize: 12,
      fontFamily: fonts.medium,
      color: colors.gray,
    },
    statusTextActive: {
      color: colors.text,
      fontFamily: fonts.semibold,
    },
    calendarCard: {
      backgroundColor: cardBg,
      borderRadius: 18,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      overflow: 'hidden',
      ...panelShadow,
    },
    weekdayRow: {
      flexDirection: 'row',
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: borderColor,
      backgroundColor: isDark ? 'rgba(255,255,255,0.03)' : '#FAFBFC',
    },
    weekdayCell: {
      flex: 1,
      paddingVertical: 11,
      alignItems: 'center',
      justifyContent: 'center',
    },
    weekdayText: {
      fontSize: 11,
      fontFamily: fonts.semibold,
      color: colors.gray,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    calendarGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    dayCell: {
      width: `${100 / 7}%`,
      minHeight: hp(10.5),
      borderRightWidth: StyleSheet.hairlineWidth,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor,
      paddingHorizontal: 4,
      paddingTop: 6,
      paddingBottom: 4,
    },
    dayCellMuted: {
      backgroundColor: isDark ? 'rgba(255,255,255,0.02)' : '#FCFCFD',
    },
    dayCellToday: {
      backgroundColor: isDark ? `${colors.primary}14` : `${colors.primary}08`,
    },
    dayNumberWrap: {
      alignSelf: 'flex-end',
      minWidth: 24,
      height: 24,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 4,
    },
    dayNumberWrapToday: {
      backgroundColor: colors.primary,
    },
    dayNumber: {
      fontSize: 12,
      fontFamily: fonts.medium,
      color: colors.text,
    },
    dayNumberMuted: {
      color: colors.gray,
    },
    dayNumberToday: {
      color: colors.white,
      fontFamily: fonts.bold,
    },
    eventCountBadge: {
      position: 'absolute',
      top: 4,
      left: 4,
      minWidth: 16,
      height: 16,
      borderRadius: 8,
      paddingHorizontal: 4,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
    },
    eventCountText: {
      fontSize: 9,
      fontFamily: fonts.bold,
      color: colors.white,
    },
    eventPill: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 7,
      paddingHorizontal: 5,
      paddingVertical: 3,
      marginBottom: 3,
      gap: 4,
      maxWidth: '100%',
      borderWidth: StyleSheet.hairlineWidth,
    },
    eventPillUpcoming: {
      backgroundColor: upcomingBg,
      borderColor: upcomingBorder,
    },
    eventPillPast: {
      backgroundColor: pastBg,
      borderColor: pastBorder,
    },
    eventPillCancelled: {
      backgroundColor: cancelledBg,
      borderColor: cancelledBorder,
      opacity: 0.85,
    },
    eventPillSelected: {
      borderWidth: 1.5,
      borderColor: colors.primary,
    },
    eventDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      flexShrink: 0,
    },
    eventText: {
      fontSize: 10,
      fontFamily: fonts.semibold,
      color: colors.text,
      flexShrink: 1,
    },
    moreEventsText: {
      fontSize: 9,
      fontFamily: fonts.semibold,
      color: colors.primary,
      marginTop: 1,
    },
    dayViewCard: {
      backgroundColor: cardBg,
      borderRadius: 18,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      padding: wp(3.5),
      gap: 10,
      ...panelShadow,
    },
    dayViewHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingBottom: hp(1),
      marginBottom: hp(0.5),
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: borderColor,
    },
    dayViewTitle: {
      fontSize: 16,
      fontFamily: fonts.bold,
      color: colors.text,
    },
    dayViewCount: {
      fontSize: 12,
      fontFamily: fonts.semibold,
      color: colors.primary,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
      backgroundColor: `${colors.primary}12`,
    },
    dayEventRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      paddingVertical: 12,
      paddingHorizontal: wp(2.5),
      borderRadius: 14,
      marginBottom: 8,
      backgroundColor: isDark ? 'rgba(255,255,255,0.03)' : colors.inputBg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
    },
    dayEventRowPressed: {
      opacity: 0.92,
    },
    dayEventTimeWrap: {
      alignItems: 'center',
      minWidth: 48,
    },
    dayEventTime: {
      fontSize: 13,
      fontFamily: fonts.bold,
      color: colors.primary,
    },
    dayEventTimePeriod: {
      fontSize: 10,
      fontFamily: fonts.medium,
      color: colors.gray,
      marginTop: 1,
    },
    dayEventBody: {
      flex: 1,
      gap: 4,
    },
    dayEventTitle: {
      fontSize: 15,
      fontFamily: fonts.semibold,
      color: colors.text,
    },
    dayEventMeta: {
      fontSize: 13,
      fontFamily: fonts.regular,
      color: colors.gray,
    },
    statusPill: {
      alignSelf: 'flex-start',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 20,
      marginTop: 2,
    },
    statusPillText: {
      fontSize: 10,
      fontFamily: fonts.semibold,
      letterSpacing: 0.4,
    },
    dayEventChevron: {
      width: 30,
      height: 30,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : cardBg,
      marginTop: 2,
    },
    emptyDayState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: hp(6),
      gap: 10,
    },
    emptyDayIconWrap: {
      width: 64,
      height: 64,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyDayTitle: {
      fontSize: 16,
      fontFamily: fonts.semibold,
      color: colors.text,
    },
    emptyDaySubtitle: {
      fontSize: 13,
      fontFamily: fonts.regular,
      color: colors.gray,
      textAlign: 'center',
      paddingHorizontal: wp(8),
      lineHeight: 20,
    },
    errorBanner: {
      marginBottom: hp(1.2),
      padding: 14,
      borderRadius: 14,
      backgroundColor: isDark ? 'rgba(239, 68, 68, 0.14)' : '#FEF2F2',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? 'rgba(239, 68, 68, 0.35)' : '#FECACA',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    errorText: {
      flex: 1,
      fontSize: 13,
      fontFamily: fonts.medium,
      color: colors.danger,
    },
  })
}
