import { StyleSheet } from 'react-native'
import { fonts } from '../../../constant'
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from '../../../theme/layout'
import { createSettingsScreenStyles } from '../shared/settingsScreenTheme'

export const getListStyles = (colors, isDark = false, options = {}) =>
  StyleSheet.create({
    ...createSettingsScreenStyles(colors, isDark, options),
    newImportBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
      backgroundColor: colors.primary,
      borderRadius: 12,
      paddingVertical: hp(1.7),
      gap: 8,
      marginBottom: hp(2),
    },
    newImportBtnText: {
      color: colors.white,
      fontFamily: fonts.semibold,
      fontSize: 14,
      letterSpacing: 0.2,
    },
    toolbar: {
      gap: hp(1.2),
      marginBottom: hp(1.8),
    },
    toolbarBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: hp(1.1),
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      backgroundColor: colors.cardBg,
    },
    toolbarBtnText: {
      color: colors.appText || colors.text,
      fontFamily: fonts.semibold,
      fontSize: 12,
    },
    pageSizeRow: {
      gap: 8,
    },
    pageSizeChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : colors.inputBg,
    },
    pageSizeChipActive: {
      borderColor: `${colors.primary}40`,
      backgroundColor: isDark ? `${colors.primary}28` : `${colors.primary}14`,
    },
    pageSizeChipText: {
      color: colors.gray,
      fontFamily: fonts.medium,
      fontSize: 11,
    },
    pageSizeChipTextActive: {
      color: colors.primary,
      fontFamily: fonts.semibold,
    },
    sessionList: {
      gap: 10,
    },
    sessionCard: {
      backgroundColor: colors.cardBg,
      borderRadius: 16,
      padding: wp(4),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
    },
    sessionCardPressed: {
      opacity: 0.92,
    },
    sessionTopRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: wp(2.5),
      marginBottom: hp(1.2),
    },
    fileIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: `${colors.primary}12`,
    },
    sessionBody: {
      flex: 1,
      minWidth: 0,
    },
    filename: {
      color: colors.appText || colors.text,
      fontFamily: fonts.semibold,
      fontSize: 14,
      marginBottom: 2,
    },
    createdAt: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 11,
    },
    statusBadge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 20,
      borderWidth: StyleSheet.hairlineWidth,
    },
    statusBadgeText: {
      fontFamily: fonts.semibold,
      fontSize: 10,
      textTransform: 'uppercase',
      letterSpacing: 0.3,
    },
    metricsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingTop: hp(1),
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.surfaceBorder || colors.border,
      marginBottom: hp(1),
    },
    metricItem: {
      alignItems: 'center',
      flex: 1,
    },
    metricValue: {
      color: colors.appText || colors.text,
      fontFamily: fonts.bold,
      fontSize: 13,
    },
    metricLabel: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 10,
      marginTop: 2,
    },
    viewRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 4,
    },
    viewText: {
      color: colors.primary,
      fontFamily: fonts.semibold,
      fontSize: 12,
    },
    pagination: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 16,
      marginTop: hp(2),
    },
    pageBtn: {
      width: 38,
      height: 38,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.cardBg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
    },
    pageBtnDisabled: {
      opacity: 0.45,
    },
    pageLabel: {
      color: colors.appText || colors.text,
      fontFamily: fonts.medium,
      fontSize: 13,
    },
    detailHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: hp(1.8),
    },
    detailTitle: {
      flex: 1,
      color: colors.appText || colors.text,
      fontFamily: fonts.bold,
      fontSize: 17,
    },
    progressCard: {
      backgroundColor: colors.cardBg,
      borderRadius: 16,
      padding: wp(4),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      marginBottom: hp(2),
    },
    progressTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: hp(0.8),
    },
    progressLabel: {
      color: colors.gray,
      fontFamily: fonts.medium,
      fontSize: 12,
    },
    progressPercent: {
      color: colors.appText || colors.text,
      fontFamily: fonts.bold,
      fontSize: 14,
    },
    progressTrack: {
      height: 8,
      borderRadius: 4,
      backgroundColor: isDark ? 'rgba(255,255,255,0.08)' : colors.inputBg,
      overflow: 'hidden',
      marginBottom: hp(0.8),
    },
    progressFill: {
      height: '100%',
      borderRadius: 4,
    },
    progressText: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 12,
    },
    summaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: hp(2),
    },
    summaryCard: {
      width: '48%',
      flexGrow: 1,
      backgroundColor: colors.cardBg,
      borderRadius: 14,
      padding: wp(3.5),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      minWidth: wp(42),
    },
    summaryIcon: {
      width: 32,
      height: 32,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: hp(0.8),
    },
    summaryLabel: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 11,
      marginBottom: 4,
    },
    summaryValue: {
      color: colors.appText || colors.text,
      fontFamily: fonts.semibold,
      fontSize: 13,
    },
    summarySubvalue: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 11,
      marginTop: 2,
    },
    statsCard: {
      backgroundColor: colors.cardBg,
      borderRadius: 16,
      padding: wp(4),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      marginBottom: hp(2),
      gap: hp(0.8),
    },
    statRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    statLabel: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 13,
    },
    statValue: {
      color: colors.appText || colors.text,
      fontFamily: fonts.semibold,
      fontSize: 13,
    },
    errorCard: {
      backgroundColor: isDark ? `${colors.danger || '#DC2626'}12` : `${colors.danger || '#DC2626'}08`,
      borderRadius: 14,
      padding: wp(4),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: `${colors.danger || '#DC2626'}35`,
      marginBottom: hp(2),
    },
    errorTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: hp(0.6),
    },
    errorTitle: {
      color: colors.danger || '#DC2626',
      fontFamily: fonts.semibold,
      fontSize: 14,
    },
    errorText: {
      color: colors.appText || colors.text,
      fontFamily: fonts.regular,
      fontSize: 13,
      lineHeight: 19,
    },
    footerRow: {
      flexDirection: 'row',
      gap: 10,
      marginTop: hp(0.5),
    },
    secondaryBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: 12,
      paddingVertical: hp(1.6),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      backgroundColor: colors.cardBg,
    },
    secondaryBtnText: {
      color: colors.appText || colors.text,
      fontFamily: fonts.semibold,
      fontSize: 13,
    },
  })

export default getListStyles
