import { StyleSheet } from 'react-native';
import { fonts } from '../../../constant';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from '../../../theme/layout';

export const getStyles = (colors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.dark,
  },
  // Empty State Styles
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: wp(5),
  },
  emptyStateTitle: {
    fontSize: 20,
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: hp(1),
    textAlign: 'center',
  },
  emptyStateSubtitle: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: colors.gray,
    marginBottom: hp(4),
    textAlign: 'center',
  },
  newImportButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: wp(8),
    paddingVertical: 16,
    borderRadius: hp(1.5),
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  newImportButtonText: {
    color: colors.white,
    fontSize: 16,
    fontFamily: fonts.medium,
  },
  // Step-based UI Styles
  stepContainer: {
    flex: 1,
    paddingHorizontal: wp(5),
    paddingTop: hp(2),
  },
  stepHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(3),
  },
  stepTitle: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: colors.white,
    textAlign: 'center',
  },
  stepIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stepNumber: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: colors.primary,
  },
  stepTotal: {
    fontSize: 16,
    fontFamily: fonts.regular,
    color: colors.gray,
    marginLeft: wp(1),
  },
  backButton: {
    paddingHorizontal: wp(2),
  },
  backButtonText: {
    color: colors.primary,
    fontSize: 16,
    fontFamily: fonts.medium,
  },
  // Step 1 Styles
  uploadContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: wp(5),
  },
  uploadButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: wp(15),
    paddingVertical: hp(3),
    borderRadius: hp(2),
    borderWidth: 2,
    borderColor: colors.primary,
    borderStyle: 'dashed',
    marginBottom: hp(2),
  },
  uploadButtonText: {
    color: colors.white,
    fontSize: hp(2.2),
    fontFamily: fonts.medium,
  },
  uploadHint: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: colors.gray,
    textAlign: 'center',
  },
  selectedFileContainer: {
    backgroundColor: colors.light,
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    borderRadius: hp(1),
    marginBottom: hp(2),
    alignItems: 'center',
  },
  selectedFileName: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: colors.dark,
    marginBottom: hp(0.5),
    textAlign: 'center',
  },
  // Step 2 and 3 Styles
  mappingContainer: {
    flex: 1,
    paddingHorizontal: wp(2),
  },
  mappingTitle: {
    fontSize: hp(2.2),
    fontFamily: fonts.bold,
    color: colors.white,
    textAlign: 'center',
    marginBottom: hp(3),
  },
  mappingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.light,
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    borderRadius: hp(1),
    marginBottom: hp(1.5),
  },
  columnHeaderContainer: {
    flex: 1,
  },
  columnHeader: {
    fontSize: hp(2),
    fontFamily: fonts.bold,
    color: colors.dark,
    marginBottom: hp(0.5),
  },
  sampleData: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: colors.gray,
  },
  dropdownContainer: {
    width: wp(35),
  },
  dropdownText: {
    fontSize: 14,
    fontFamily: fonts.medium,
    color: colors.dark,
    textAlign: 'center',
  },
  dropdownOptions: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.gray,
    borderRadius: hp(0.8),
    marginTop: hp(0.5),
    zIndex: 1000,
    maxHeight: hp(20),
  },
  dropdownOption: {
    paddingHorizontal: wp(3),
    paddingVertical: hp(1.2),
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
  },
  dropdownOptionSelected: {
    backgroundColor: colors.primary,
  },
  dropdownOptionText: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: colors.dark,
    textAlign: 'center',
  },
  dropdownOptionTextSelected: {
    color: colors.white,
    fontFamily: fonts.medium,
  },
  summaryContainer: {
    flex: 1,
    paddingHorizontal: wp(2),
  },
  summaryTitle: {
    fontSize: hp(2.5),
    fontFamily: fonts.bold,
    color: colors.white,
    textAlign: 'center',
    marginBottom: hp(1),
  },
  summarySubtitle: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: colors.gray,
    textAlign: 'center',
    marginBottom: hp(4),
  },
  fileInfoCard: {
    backgroundColor: colors.light,
    paddingHorizontal: wp(4),
    paddingVertical: hp(3),
    borderRadius: hp(1),
    marginBottom: hp(3),
  },
  cardTitle: {
    fontSize: hp(2.2),
    fontFamily: fonts.bold,
    color: colors.dark,
    marginBottom: hp(2),
  },
  fileInfo: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: colors.dark,
    marginBottom: hp(1),
  },
  mappingCard: {
    backgroundColor: colors.light,
    paddingHorizontal: wp(4),
    paddingVertical: hp(3),
    borderRadius: hp(1),
    marginBottom: hp(3),
  },
  mappingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(1.5),
  },
  mappingHeader: {
    fontSize: 14,
    fontFamily: fonts.medium,
    color: colors.dark,
    flex: 1,
  },
  mappingArrow: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: colors.primary,
    marginHorizontal: wp(2),
  },
  mappingField: {
    fontSize: 14,
    fontFamily: fonts.medium,
    color: colors.success,
    flex: 1,
    textAlign: 'right',
  },
  previewCard: {
    backgroundColor: colors.light,
    paddingHorizontal: wp(4),
    paddingVertical: hp(3),
    borderRadius: hp(1),
    marginBottom: hp(3),
  },
  previewRow: {
    marginBottom: hp(1.5),
    paddingBottom: hp(1.5),
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
  },
  previewItem: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: colors.dark,
    marginBottom: hp(0.5),
  },
  previewKey: {
    fontFamily: fonts.bold,
  },
  successContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: wp(5),
  },
  successIcon: {
    fontSize: hp(8),
    color: colors.success,
    marginBottom: hp(2),
  },
  successTitle: {
    fontSize: hp(3),
    fontFamily: fonts.bold,
    color: colors.white,
    textAlign: 'center',
    marginBottom: hp(1),
  },
  successSubtitle: {
    fontSize: 16,
    fontFamily: fonts.regular,
    color: colors.gray,
    textAlign: 'center',
    marginBottom: hp(4),
  },
  nextButton: {
    backgroundColor: colors.success,
    paddingHorizontal: wp(8),
    paddingVertical: hp(2),
    borderRadius: hp(1.5),
    alignSelf: 'center',
    marginTop: hp(3),
  },
  nextButtonText: {
    color: colors.white,
    fontSize: 16,
    fontFamily: fonts.medium,
  },
  // Step 2 Styles
  resultsContainer: {
    flex: 1,
    paddingHorizontal: wp(5),
  },
  resultsTitle: {
    fontSize: hp(2.5),
    fontFamily: fonts.bold,
    color: colors.white,
    textAlign: 'center',
    marginBottom: hp(4),
  },
  resultItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.light,
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    borderRadius: hp(1),
    marginBottom: hp(1.5),
  },
  resultLabel: {
    fontSize: hp(2),
    fontFamily: fonts.medium,
    color: colors.dark,
  },
  resultValue: {
    fontSize: hp(2),
    fontFamily: fonts.bold,
    color: colors.primary,
  },
  finishButton: {
    backgroundColor: colors.success,
    paddingHorizontal: wp(12),
    paddingVertical: hp(2.5),
    borderRadius: hp(1.5),
    alignSelf: 'center',
    marginTop: hp(4),
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  finishButtonText: {
    color: colors.white,
    fontSize: hp(2.2),
    fontFamily: fonts.bold,
  },
  // Bottom Button Layout
  bottomButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp(5),
    paddingVertical: hp(2),
    backgroundColor: colors.dark,
    borderTopWidth: 1,
    borderTopColor: colors.light,
  },
  bottomBackButton: {
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.5),
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: hp(1),
  },
  bottomBackButtonText: {
    color: colors.primary,
    fontSize: 16,
    fontFamily: fonts.medium,
  },
  // Enhanced Step Indicator Styles
  stepIndicatorContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: hp(2),
    paddingHorizontal: wp(5),
  },
  stepWrapper: {
    alignItems: 'center',
    width: wp(25),
  },
  stepConnectorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: hp(0.5),
  },
  stepConnector: {
    height: 2,
    backgroundColor: colors.gray,
    flex:1
  },
  stepConnectorActive: {
    backgroundColor: colors.primary,
  },
  stepCircle: {
    width: wp(7),
    height: wp(7),
    borderRadius: wp(3.5),
    backgroundColor: colors.gray,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: wp(1),
  },
  stepCircleActive: {
    backgroundColor: colors.primary,
  },
  stepNumber: {
    fontSize: 12,
    fontFamily: fonts.bold,
    color: colors.white,
  },
  stepNumberActive: {
    color: colors.white,
  },
  stepTitle: {
    fontSize: 11,
    fontFamily: fonts.regular,
    color: colors.gray,
    textAlign: 'center',
    lineHeight: 14,
  },
  stepTitleActive: {
    color: colors.primary,
    fontFamily: fonts.medium,
    
  },
  // Enhanced Mapping UI Styles
  mappingContainer: {
    flex: 1,
    paddingHorizontal: wp(5),
    paddingBottom: hp(10), // Increased bottom padding for dropdown space
  },
  mappingTitle: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: colors.white,
  },
  mappingSubtitle: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: colors.gray,
    marginBottom: hp(2),
    lineHeight: 20,
  },
  mappingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.light,
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    borderRadius: hp(1),
    marginBottom: hp(2),
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
  },
  columnInfo: {
    flex: 1,
    marginRight: wp(3),
  },
  columnHeader: {
    fontSize: hp(2),
    fontFamily: fonts.bold,
    color: colors.dark,
    marginBottom: hp(0.5),
  },
  sampleData: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: colors.gray,
    backgroundColor: colors.white,
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.5),
    borderRadius: hp(0.5),
  },
  mappingSelector: {
    width: wp(40),
    position: 'relative',
  },
  dropdownButton: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.gray,
    borderRadius: hp(1),
    paddingHorizontal: wp(3),
    paddingVertical: hp(1.5),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dropdownButtonActive: {
    borderColor: colors.primary,
    borderWidth: 2,
  },
  dropdownText: {
    fontSize: 14,
    fontFamily: fonts.medium,
    color: colors.dark,
    flex: 1,
  },
  dropdownIcon: {
    fontSize: 12,
    color: colors.gray,
    marginLeft: wp(2),
  },
  dropdownOptions: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.gray,
    borderRadius: hp(1),
    marginTop: hp(0.5),
    zIndex: 1000,
    maxHeight: hp(25),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  dropdownOption: {
    paddingHorizontal: wp(3),
    paddingVertical: hp(1.2),
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGray,
  },
  dropdownOptionSelected: {
    backgroundColor: colors.primary,
  },
  dropdownOptionText: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: colors.dark,
  },
  dropdownOptionTextSelected: {
    color: colors.white,
    fontFamily: fonts.medium,
  },
  mappingHelp: {
    backgroundColor: colors.light,
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    borderRadius: hp(1),
    marginTop: hp(2),
  },
  helpTitle: {
    fontSize: hp(2),
    fontFamily: fonts.bold,
    color: colors.primary,
    marginBottom: hp(1),
  },
  helpText: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: colors.dark,
    marginBottom: hp(0.5),
    lineHeight: 18,
  },
  // Summary Screen Styles
  summaryContainer: {
    flex: 1,
    paddingHorizontal: wp(5),
    paddingBottom: hp(10), // Increased bottom padding for dropdown space
  },
  summaryTitle: {
    fontSize: hp(2.5),
    fontFamily: fonts.bold,
    color: colors.white,
    textAlign: 'center',
    marginBottom: hp(1),
  },
  summarySubtitle: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: colors.gray,
    textAlign: 'center',
    marginBottom: hp(4),
    lineHeight: 20,
  },
  fileInfoCard: {
    backgroundColor: colors.light,
    paddingHorizontal: wp(4),
    paddingVertical: hp(3),
    borderRadius: hp(1),
    marginBottom: hp(3),
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
  },
  mappingCard: {
    backgroundColor: colors.light,
    paddingHorizontal: wp(4),
    paddingVertical: hp(3),
    borderRadius: hp(1),
    marginBottom: hp(3),
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
  },
  mappingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(1.5),
    paddingVertical: hp(1),
  },
  mappingHeader: {
    fontSize: 14,
    fontFamily: fonts.medium,
    color: colors.dark,
    flex: 1,
  },
  mappingArrow: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: colors.primary,
    marginHorizontal: wp(2),
  },
  mappingField: {
    fontSize: 14,
    fontFamily: fonts.medium,
    color: colors.success,
    flex: 1,
    textAlign: 'right',
  },
  mappingFieldIgnored: {
    color: colors.gray,
    fontStyle: 'italic',
  },
  previewCard: {
    backgroundColor: colors.light,
    paddingHorizontal: wp(4),
    paddingVertical: hp(3),
    borderRadius: hp(1),
    marginBottom: hp(3),
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
  },
  previewRow: {
    marginBottom: hp(1.5),
    paddingBottom: hp(1.5),
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGray,
  },
  previewRowTitle: {
    fontSize: 12,
    fontFamily: fonts.bold,
    color: colors.info,
    textAlign: 'center',
  },
  previewKey: {
    fontFamily: fonts.bold,
    color: colors.info,
  },
  importWarning: {
    backgroundColor: '#FFF3CD',
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    borderRadius: hp(1),
    marginTop: hp(2),
    borderLeftWidth: 4,
    borderLeftColor: '#FFC107',
  },
  warningTitle: {
    fontSize: hp(2),
    fontFamily: fonts.bold,
    color: '#856404',
    marginBottom: hp(1),
  },
  // Table Styles for CSV Data Display
  tableContainer: {
    backgroundColor: "#1B2636",
    borderRadius: hp(1.2),
    paddingHorizontal: wp(3),
    paddingVertical: hp(2),
    marginBottom: hp(2),
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    maxHeight: hp(80), // Increased to allow more space for dropdowns
  },
  tableDataContainer: {
    maxHeight: hp(40),
    borderWidth: 1,
    borderColor: colors.lightGray,
    borderRadius: hp(0.8),
    backgroundColor: colors.white,
  },
  tableTitle: {
    fontSize: hp(2.2),
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: hp(2),
    textAlign: 'center',
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.gray,
    paddingVertical: hp(1),
    backgroundColor: colors.info,
    borderRadius: hp(0.8),
    zIndex: 50,
  },
  tableHeaderColumn: {
    minWidth: wp(30), 
    alignItems: 'center',
    paddingHorizontal: wp(2),
  },
  tableHeaderText: {
    fontSize: 12,
    fontFamily: fonts.bold,
    color: colors.dark,
    marginBottom: hp(0.5),
    textAlign: 'center',
  },
  headerMappingSelector: {
    width: '100%',
    position: 'relative',
    zIndex: 100,
  },
  dropdownButton: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.gray,
    borderRadius: hp(0.8),
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.8),
    minHeight: hp(4),
    width: '100%',
  },
  dropdownButtonActive: {
    borderColor: colors.success,
    borderWidth: 2,
  },
  dropdownText: {
    fontSize: 11,
    fontFamily: fonts.medium,
    color: colors.dark,
    textAlign: 'center',
  },
  dropdownOptions: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.gray,
    borderRadius: hp(0.8),
    marginTop: hp(0.3),
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
  },
  dropdownOption: {
    paddingHorizontal: wp(3),
    paddingVertical: hp(1),
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: hp(4),
    borderBottomWidth: 0.5,
    borderBottomColor: colors.lightGray,
  },
  dropdownOptionSelected: {
    backgroundColor: colors.info,
  },
  dropdownOptionText: {
    fontSize: 11,
    fontFamily: fonts.regular,
    color: colors.dark,
    textAlign: 'center',
    lineHeight: 14,
  },
  dropdownOptionTextSelected: {
    color: colors.white,
    fontFamily: fonts.medium,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderBottomColor: colors.gray,
    backgroundColor: "#131F31",
    minHeight: hp(5),
  },
  tableCell: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: wp(1),
    paddingVertical: hp(0.5),
    borderRightWidth: 0.5,
    borderRightColor: colors.gray,
    minWidth: wp(20),
  },
  tableCellText: {
    fontSize: 10,
    fontFamily: fonts.regular,
    color: colors.white,
    textAlign: 'center',
    flexWrap: 'wrap',
  },
  tableFirstRow: {
    backgroundColor: 'red',
  },
  tableFooter: {
    backgroundColor: colors.light,
    paddingHorizontal: wp(3),
    paddingVertical: hp(1.5),
    borderTopWidth: 1,
    borderTopColor: colors.gray,
    marginTop: hp(1),
    borderRadius: hp(0.8),
  },
  tableSummary: {
    fontSize: 12,
    fontFamily: fonts.medium,
    color: colors.primary,
    textAlign: 'center',
  },
  importProgressWrap: {
    marginBottom: hp(1.5),
    gap: hp(0.6),
  },
  importProgressTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.inputBg || colors.border,
    overflow: 'hidden',
  },
  importProgressFill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  importProgressText: {
    color: colors.gray,
    fontFamily: fonts.regular,
    fontSize: 12,
    textAlign: 'center',
  },
  successSubtitle: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: colors.gray,
    textAlign: 'center',
    marginBottom: hp(2.5),
    paddingHorizontal: wp(6),
    lineHeight: 19,
  },
  successBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(6),
    marginBottom: hp(1),
    minWidth: wp(70),
  },
  successBtnText: {
    color: colors.white,
    fontFamily: fonts.semibold,
    fontSize: 14,
  },
  successBtnSecondary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 12,
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(6),
    marginBottom: hp(1.5),
    minWidth: wp(70),
    borderWidth: 1,
    borderColor: `${colors.primary}40`,
    backgroundColor: `${colors.primary}10`,
  },
  successBtnSecondaryText: {
    color: colors.primary,
    fontFamily: fonts.semibold,
    fontSize: 14,
  },
  successLink: {
    paddingVertical: hp(1),
  },
  successLinkText: {
    color: colors.primary,
    fontFamily: fonts.medium,
    fontSize: 13,
  },
});

export default getStyles;
