import { StyleSheet, Platform } from 'react-native'
import { fonts } from '../../../constant'
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from '../../../theme/layout'
import { createSettingsScreenStyles, cardShadow } from '../shared/settingsScreenTheme'
import { normalizeStyleOptions } from '../../../theme/layout'

export const getWizardStyles = (colors, isDark = false, options = {}) => {
  const { bottomInset = 0 } = normalizeStyleOptions(options)

  return StyleSheet.create({
    ...createSettingsScreenStyles(colors, isDark, options),
    stepIndicatorContainer: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: hp(2.2),
      paddingHorizontal: wp(1),
    },
    stepWrapper: {
      flex: 1,
      alignItems: 'center',
    },
    stepConnectorContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      justifyContent: 'center',
      marginBottom: hp(0.6),
    },
    stepConnector: {
      flex: 1,
      height: 2,
      backgroundColor: colors.surfaceBorder || colors.border,
      marginHorizontal: 4,
    },
    stepConnectorActive: {
      backgroundColor: colors.primary,
    },
    stepCircle: {
      width: 32,
      height: 32,
      borderRadius: 16,
      borderWidth: 2,
      borderColor: colors.surfaceBorder || colors.border,
      backgroundColor: colors.cardBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepCircleActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primary,
    },
    stepCircleCurrent: {
      borderColor: colors.primary,
      backgroundColor: isDark ? `${colors.primary}20` : `${colors.primary}12`,
    },
    stepNumber: {
      fontSize: 13,
      fontFamily: fonts.bold,
      color: colors.gray,
    },
    stepNumberActive: {
      color: colors.white,
    },
    stepNumberCurrent: {
      color: colors.primary,
    },
    stepLabel: {
      fontSize: 11,
      fontFamily: fonts.medium,
      color: colors.gray,
      textAlign: 'center',
    },
    stepLabelActive: {
      color: colors.primary,
      fontFamily: fonts.semibold,
    },
    uploadCard: {
      backgroundColor: colors.cardBg,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: `${colors.primary}35`,
      borderStyle: 'dashed',
      paddingVertical: hp(4),
      paddingHorizontal: wp(5),
      alignItems: 'center',
      marginBottom: hp(1.5),
      ...cardShadow(isDark),
    },
    uploadIconWrap: {
      width: 56,
      height: 56,
      borderRadius: 16,
      backgroundColor: isDark ? `${colors.primary}20` : `${colors.primary}12`,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: hp(1.4),
    },
    uploadTitle: {
      color: colors.appText || colors.text,
      fontFamily: fonts.semibold,
      fontSize: 16,
      marginBottom: hp(0.5),
      textAlign: 'center',
    },
    uploadHint: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 13,
      textAlign: 'center',
      lineHeight: 19,
      marginBottom: hp(1.6),
    },
    chooseFileBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: colors.primary,
      borderRadius: 12,
      paddingVertical: hp(1.5),
      paddingHorizontal: wp(6),
      minWidth: wp(50),
    },
    chooseFileBtnText: {
      color: colors.white,
      fontFamily: fonts.semibold,
      fontSize: 14,
    },
    selectedFileCard: {
      width: '100%',
      backgroundColor: isDark ? `${colors.success}12` : `${colors.success}08`,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: `${colors.success}35`,
      padding: wp(3.5),
      marginTop: hp(1.5),
      flexDirection: 'row',
      alignItems: 'center',
      gap: wp(2.5),
    },
    selectedFileContent: {
      flex: 1,
    },
    selectedFileName: {
      flex: 1,
      color: colors.appText || colors.text,
      fontFamily: fonts.semibold,
      fontSize: 13,
    },
    selectedFileSize: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 11,
    },
    mappingList: {
      gap: hp(1),
      marginBottom: hp(1.5),
    },
    mappingRow: {
      backgroundColor: colors.cardBg,
      borderRadius: 14,
      padding: wp(3.5),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      ...cardShadow(isDark),
    },
    mappingRowHeader: {
      color: colors.appText || colors.text,
      fontFamily: fonts.semibold,
      fontSize: 13,
    },
    mappingRowTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 4,
    },
    statusBadge: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 6,
      borderWidth: StyleSheet.hairlineWidth,
    },
    statusBadgeText: {
      fontFamily: fonts.semibold,
      fontSize: 10,
      textTransform: 'uppercase',
      letterSpacing: 0.3,
    },
    dropdown: {
      backgroundColor: colors.inputBg,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      paddingHorizontal: wp(3),
      height: hp(5.2),
    },
    dropdownText: {
      color: colors.appText || colors.text,
      fontFamily: fonts.regular,
      fontSize: 13,
    },
    dropdownPlaceholder: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 13,
    },
    dropdownContainer: {
      backgroundColor: colors.cardBg,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      marginTop: 4,
    },
    dropdownItemText: {
      color: colors.text,
      fontFamily: fonts.regular,
      fontSize: 13,
    },
    previewTableCard: {
      backgroundColor: colors.cardBg,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      overflow: 'hidden',
      marginBottom: hp(1.5),
      ...cardShadow(isDark),
    },
    previewTableHeader: {
      flexDirection: 'row',
      backgroundColor: isDark ? `${colors.primary}15` : `${colors.primary}08`,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.surfaceBorder || colors.border,
    },
    previewTableHeaderCell: {
      minWidth: wp(28),
      paddingVertical: hp(1),
      paddingHorizontal: wp(2.5),
      borderRightWidth: StyleSheet.hairlineWidth,
      borderRightColor: colors.surfaceBorder || colors.border,
    },
    previewTableHeaderText: {
      color: colors.appText || colors.text,
      fontFamily: fonts.semibold,
      fontSize: 11,
    },
    previewTableRow: {
      flexDirection: 'row',
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.surfaceBorder || colors.border,
    },
    previewTableCell: {
      minWidth: wp(28),
      paddingVertical: hp(0.9),
      paddingHorizontal: wp(2.5),
      borderRightWidth: StyleSheet.hairlineWidth,
      borderRightColor: colors.surfaceBorder || colors.border,
    },
    previewTableCellText: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 11,
    },
    previewFooter: {
      padding: wp(3),
      backgroundColor: isDark ? 'rgba(255,255,255,0.03)' : colors.inputBg,
    },
    previewFooterText: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 11,
      textAlign: 'center',
    },
    summaryRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: hp(0.7),
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.surfaceBorder || colors.border,
    },
    summaryRowLast: {
      borderBottomWidth: 0,
    },
    summaryKey: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 13,
      flex: 1,
    },
    summaryValue: {
      color: colors.appText || colors.text,
      fontFamily: fonts.medium,
      fontSize: 13,
      textAlign: 'right',
      flex: 1,
    },
    summaryValueIgnored: {
      color: colors.gray,
      fontStyle: 'italic',
    },
    importProgressWrap: {
      marginBottom: hp(1.5),
      gap: hp(0.6),
    },
    importProgressTrack: {
      height: 8,
      borderRadius: 4,
      backgroundColor: isDark ? 'rgba(255,255,255,0.08)' : colors.inputBg,
      overflow: 'hidden',
    },
    importProgressFill: {
      height: '100%',
      borderRadius: 4,
      backgroundColor: colors.primary,
    },
    importProgressText: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 12,
      textAlign: 'center',
    },
    successWrap: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: wp(6),
      paddingBottom: hp(4),
    },
    successIconWrap: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: isDark ? `${colors.success}18` : `${colors.success}12`,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: hp(2),
      borderWidth: 2,
      borderColor: `${colors.success}40`,
    },
    successTitle: {
      color: colors.appText || colors.text,
      fontFamily: fonts.bold,
      fontSize: 22,
      marginBottom: hp(0.8),
      textAlign: 'center',
    },
    successSubtitle: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 14,
      textAlign: 'center',
      lineHeight: 21,
      marginBottom: hp(3),
    },
    successBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      width: '100%',
      backgroundColor: colors.primary,
      borderRadius: 12,
      paddingVertical: hp(1.6),
      marginBottom: hp(1),
    },
    successBtnText: {
      color: colors.white,
      fontFamily: fonts.semibold,
      fontSize: 14,
    },
    successBtnSecondary: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      width: '100%',
      borderRadius: 12,
      paddingVertical: hp(1.6),
      marginBottom: hp(1.5),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: `${colors.primary}35`,
      backgroundColor: isDark ? `${colors.primary}12` : `${colors.primary}08`,
    },
    successBtnSecondaryText: {
      color: colors.primary,
      fontFamily: fonts.semibold,
      fontSize: 14,
    },
    successLink: {
      paddingVertical: hp(1),
    },
    successLinkText: {
      color: colors.primary,
      fontFamily: fonts.medium,
      fontSize: 13,
    },
    wizardFooter: {
      flexDirection: 'row',
      gap: 10,
      paddingTop: hp(1.5),
      paddingBottom: Math.max(hp(1), bottomInset > 0 ? 0 : hp(1)),
      marginTop: hp(1),
    },
    btnDisabled: {
      opacity: 0.55,
    },
  })
}

export default getWizardStyles
