
export const colors = {
    primary: "#3B82F6",   
    secondary: "#F5F6FA", 
    accent: "#0D0F62",    
    success: "#10B981",   
    danger: "#EF4444",    
    warning: "#F97316",   
    info: "#0288d1",    
    gray: "#B5B8BD",
    green:"#10B981", 
    active:"#85E288",
    inactive:"#FFC107",   
    light: "#F3F4F6",    
    dark: "#1A1D23",      
    white: "#FFFFFF",
    black: "#000000",
    orange:"#F97316",
    element1:"#EF4444",
    element2:"#10B981",
    gr:"#85E288",
    red:"#EF4444",
  };
export const fonts = {
    regular: 'Poppins-Regular',
    medium: 'Poppins-Medium',
    bold: 'Poppins-Bold',
    semibold: 'Poppins-SemiBold',
  };

export const images = {
  logo:require('../assets/logo.png'),
  role:require('../assets/role.png'),
  authBg:require('../assets/authBg.png'),
  menu:require('../assets/menu.png'),
  search:require('../assets/search.png'),
  bell:require('../assets/bell.png'),
  car:require('../assets/car.png'),
  empty:require('../assets/empty.png'),
  channel:require('../assets/channel.png'),
  users:require('../assets/users.png'),
  ivr:require('../assets/ivr.png'),
  settings:require('../assets/settings.png'),
  analytics:require('../assets/analytics.png'),
  logs:require('../assets/logs.png'),
  calendar:require('../assets/calendar.png'),
  phone:require('../assets/phone.png'),
  office:require('../assets/office.png'),
  ai:require('../assets/ai.png'),
  img:require('../assets/img.png'),
  img2:require('../assets/img2.png'),
  user:require('../assets/user.png'),
  orga:require('../assets/orga.png'),
  subs:require('../assets/subs.png'),
  invo:require('../assets/invo.png'),
  fa:require('../assets/2fa.png'),
}
