import { StyleSheet } from 'react-native'
import {
  wp,
  hp,
  normalizeStyleOptions,
  getContentMaxWidth,
  screenPadding,
} from '../../../theme/layout'
import { cardShadow } from '../../../theme/shadows'
import { fonts } from '../../../constant'

export const DNC_OK_BG = '#ECFDF5'
export const DNC_OK_BORDER = '#86EFAC'
export const DNC_OK_TEXT = '#15803D'
export const DNC_BTN_BG = '#FEF2F2'
export const DNC_BTN_BORDER = '#FECACA'

export default function getStyles(colors, isDark, options = {}) {
  const { isCompact = false, isWide = false } = normalizeStyleOptions(options)
  const padH = screenPadding(isWide, isCompact)
  const contentMaxWidth = getContentMaxWidth(isWide)
  const accent = colors.primary
  const panelBg = isDark ? colors.cardBg : '#FFFFFF'
  const pageBg = isDark ? (colors.appBg || colors.dark) : '#F1F5F9'
  const fieldBg = isDark ? colors.inputBg : '#F8FAFC'
  const fieldBorder = isDark ? colors.border : '#E2E8F0'
  const labelColor = isDark ? colors.gray : '#94A3B8'
  const titleColor = isDark ? colors.text : '#0F172A'
  const mutedText = isDark ? colors.gray : '#64748B'

  const panelShadow = cardShadow(isDark)
  const softShadow = cardShadow(isDark, 'soft')

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: pageBg,
    },
    headerGradient: {
      paddingBottom: hp(1),
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: padH,
      paddingBottom: hp(0.8),
    },
    backBtn: {
      width: wp(10),
      height: wp(10),
      borderRadius: wp(5),
      backgroundColor: isDark ? 'rgba(255,255,255,0.08)' : 'rgba(255,255,255,0.85)',
      alignItems: 'center',
      justifyContent: 'center',
      ...softShadow,
    },
    headerTitle: {
      color: isDark ? colors.text : '#0F172A',
      fontFamily: fonts.bold,
      fontSize: 20,
      letterSpacing: -0.3,
    },
    headerSpacer: {
      width: wp(10),
    },
    heroCard: {
      marginHorizontal: padH,
      marginBottom: hp(1.4),
      borderRadius: 20,
      overflow: 'hidden',
      ...panelShadow,
    },
    heroInner: {
      paddingHorizontal: wp(4.5),
      paddingVertical: hp(2),
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
    },
    heroAvatar: {
      width: wp(15),
      height: wp(15),
      borderRadius: wp(7.5),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.22)',
      borderWidth: 2,
      borderColor: 'rgba(255,255,255,0.38)',
    },
    heroAvatarText: {
      color: '#FFFFFF',
      fontFamily: fonts.bold,
      fontSize: 22,
      letterSpacing: 0.5,
    },
    heroContent: {
      flex: 1,
    },
    heroName: {
      color: '#FFFFFF',
      fontFamily: fonts.bold,
      fontSize: 18,
      letterSpacing: -0.2,
      marginBottom: 4,
    },
    heroSub: {
      color: 'rgba(255,255,255,0.82)',
      fontFamily: fonts.regular,
      fontSize: 13,
      marginBottom: 8,
    },
    heroChipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    heroChip: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.18)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.22)',
    },
    heroChipText: {
      color: '#FFFFFF',
      fontFamily: fonts.medium,
      fontSize: 11,
    },
    tabBarWrap: {
      marginHorizontal: wp(4),
      marginBottom: hp(1.2),
      borderRadius: 14,
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(255,255,255,0.92)',
      padding: 4,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.08)' : 'rgba(255,255,255,0.9)',
      ...softShadow,
    },
    tabsScroll: {
      flexGrow: 0,
    },
    tabsScrollContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 2,
    },
    tabChip: {
      paddingHorizontal: wp(3.8),
      paddingVertical: hp(1.15),
      borderRadius: 11,
      backgroundColor: 'transparent',
    },
    tabChipActive: {
      overflow: 'hidden',
    },
    tabChipGradient: {
      ...StyleSheet.absoluteFillObject,
      borderRadius: 11,
    },
    tabText: {
      color: mutedText,
      fontFamily: fonts.medium,
      fontSize: 12.5,
    },
    tabTextActive: {
      color: '#FFFFFF',
      fontFamily: fonts.semibold,
    },
    scrollContent: {
      paddingHorizontal: padH,
      paddingTop: hp(0.3),
      paddingBottom: hp(16),
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: isWide ? 'center' : 'stretch',
    },
    card: {
      backgroundColor: panelBg,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(255,255,255,0.8)',
      marginBottom: hp(1.6),
      overflow: 'hidden',
      ...panelShadow,
    },
    cardAccent: {
      height: 3,
      width: '100%',
    },
    cardBody: {
      paddingHorizontal: padH,
      paddingTop: hp(1.6),
      paddingBottom: hp(2),
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: hp(1.5),
    },
    cardHeaderLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
    },
    cardIconWrap: {
      width: wp(9),
      height: wp(9),
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    cardTitle: {
      color: titleColor,
      fontFamily: fonts.bold,
      fontSize: 15,
      letterSpacing: -0.2,
      flex: 1,
    },
    editBtn: {
      width: wp(8.5),
      height: wp(8.5),
      borderRadius: wp(4.25),
      backgroundColor: isDark ? `${accent}22` : `${accent}08`,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: isDark ? `${accent}33` : `${accent}18`,
    },
    fieldWrap: {
      marginBottom: hp(1.3),
    },
    fieldLabel: {
      color: labelColor,
      fontFamily: fonts.semibold,
      fontSize: 10,
      letterSpacing: 1.1,
      textTransform: 'uppercase',
      marginBottom: hp(0.55),
      marginLeft: 2,
    },
    fieldValue: {
      backgroundColor: fieldBg,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: fieldBorder,
      paddingHorizontal: wp(3.8),
      paddingVertical: hp(1.35),
      minHeight: hp(5.4),
      justifyContent: 'center',
    },
    fieldValueMultiline: {
      minHeight: hp(8),
      paddingVertical: hp(1.2),
    },
    fieldValueText: {
      color: titleColor,
      fontFamily: fonts.medium,
      fontSize: 14,
      lineHeight: 21,
    },
    statusRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: hp(1.4),
      paddingHorizontal: wp(3),
      paddingVertical: hp(1),
      backgroundColor: isDark ? colors.inputBg : '#F8FAFC',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: fieldBorder,
    },
    statusDot: {
      width: 9,
      height: 9,
      borderRadius: 5,
      backgroundColor: labelColor,
    },
    statusDotActive: {
      backgroundColor: accent,
    },
    statusLabel: {
      color: titleColor,
      fontFamily: fonts.semibold,
      fontSize: 14,
    },
    dncBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: isDark ? `${colors.success}14` : DNC_OK_BG,
      borderWidth: 1,
      borderColor: isDark ? `${colors.success}33` : DNC_OK_BORDER,
      borderRadius: 12,
      paddingHorizontal: wp(3.5),
      paddingVertical: hp(1.35),
      marginTop: hp(0.2),
      marginBottom: hp(1.3),
    },
    dncBannerWarning: {
      backgroundColor: isDark ? `${colors.danger}14` : DNC_BTN_BG,
      borderColor: isDark ? `${colors.danger}33` : DNC_BTN_BORDER,
    },
    dncBannerText: {
      flex: 1,
      color: isDark ? colors.success : DNC_OK_TEXT,
      fontFamily: fonts.medium,
      fontSize: 13,
      lineHeight: 18,
    },
    dncBannerTextWarning: {
      color: isDark ? colors.danger : '#B91C1C',
    },
    dncButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: 12,
      paddingVertical: hp(1.55),
      ...softShadow,
    },
    dncButtonAdd: {
      backgroundColor: colors.danger,
    },
    dncButtonRemove: {
      backgroundColor: colors.success || '#22C55E',
    },
    dncButtonText: {
      color: colors.white,
      fontFamily: fonts.semibold,
      fontSize: 14,
    },
    loadingWrap: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      gap: 12,
    },
    loadingText: {
      color: mutedText,
      fontFamily: fonts.medium,
      fontSize: 13,
    },
    tabPanel: {
      paddingTop: hp(0.3),
    },
    emptyState: {
      alignItems: 'center',
      paddingVertical: hp(5),
      paddingHorizontal: wp(8),
    },
    emptyIconWrap: {
      width: wp(18),
      height: wp(18),
      borderRadius: wp(9),
      backgroundColor: isDark ? `${accent}18` : `${accent}08`,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: hp(1.8),
      borderWidth: 1,
      borderColor: isDark ? `${accent}28` : `${accent}18`,
    },
    emptyTitle: {
      color: titleColor,
      fontFamily: fonts.semibold,
      fontSize: 16,
      marginBottom: 6,
      textAlign: 'center',
    },
    emptyText: {
      color: mutedText,
      fontFamily: fonts.regular,
      fontSize: 13,
      lineHeight: 20,
      textAlign: 'center',
    },
    noteComposerCard: {
      backgroundColor: panelBg,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: isDark ? colors.border : '#E2E8F0',
      padding: wp(3.5),
      marginBottom: hp(1.5),
      ...softShadow,
    },
    noteComposer: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 10,
    },
    noteInput: {
      flex: 1,
      minHeight: hp(6),
      maxHeight: hp(14),
      borderWidth: 1,
      borderColor: fieldBorder,
      borderRadius: 12,
      paddingHorizontal: wp(3.5),
      paddingVertical: hp(1.1),
      color: colors.text,
      backgroundColor: fieldBg,
      fontFamily: fonts.regular,
      fontSize: 14,
      lineHeight: 20,
    },
    noteSaveBtn: {
      borderRadius: 12,
      paddingHorizontal: padH,
      paddingVertical: hp(1.25),
      minWidth: wp(16),
      alignItems: 'center',
      overflow: 'hidden',
    },
    noteSaveBtnDisabled: {
      opacity: 0.45,
    },
    noteSaveText: {
      color: colors.white,
      fontFamily: fonts.semibold,
      fontSize: 13,
    },
    noteCard: {
      backgroundColor: panelBg,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: isDark ? colors.border : '#E2E8F0',
      padding: wp(3.8),
      marginBottom: hp(1.1),
      ...softShadow,
    },
    noteBody: {
      color: colors.text,
      fontFamily: fonts.regular,
      fontSize: 14,
      lineHeight: 22,
    },
    noteFooter: {
      marginTop: hp(1.1),
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: hp(0.8),
      borderTopWidth: 1,
      borderTopColor: isDark ? colors.border : '#F1F5F9',
    },
    noteMeta: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 11,
    },
    attachmentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: panelBg,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: isDark ? colors.border : '#E2E8F0',
      padding: wp(3.2),
      marginBottom: hp(1.1),
      ...softShadow,
    },
    attachmentRowMain: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      minWidth: 0,
    },
    attachmentActionBtn: {
      padding: wp(1),
    },
    attachmentThumb: {
      width: '100%',
      height: '100%',
      borderRadius: 12,
    },
    attachmentUploader: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 10,
      marginTop: 2,
    },
    attachmentUploadCard: {
      backgroundColor: panelBg,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: isDark ? colors.border : '#E2E8F0',
      padding: wp(4),
      marginBottom: hp(1.6),
      ...softShadow,
    },
    attachmentUploadHeader: {
      marginBottom: hp(1.2),
    },
    attachmentUploadTitle: {
      color: colors.text,
      fontFamily: fonts.semibold,
      fontSize: 15,
    },
    attachmentUploadHint: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 12,
      marginTop: 4,
    },
    attachmentBrowseBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: `${accent}44`,
      backgroundColor: isDark ? `${accent}12` : `${accent}08`,
      paddingVertical: hp(1.2),
    },
    attachmentBrowseText: {
      color: accent,
      fontFamily: fonts.semibold,
      fontSize: 13,
    },
    pendingUploadList: {
      marginTop: hp(1.4),
      gap: hp(0.8),
    },
    pendingUploadRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: hp(0.6),
    },
    pendingUploadThumb: {
      width: wp(11),
      height: wp(11),
      borderRadius: 10,
      backgroundColor: colors.border,
    },
    pendingUploadIcon: {
      width: wp(11),
      height: wp(11),
      borderRadius: 10,
      backgroundColor: isDark ? `${accent}18` : `${accent}08`,
      alignItems: 'center',
      justifyContent: 'center',
    },
    pendingUploadMeta: {
      flex: 1,
      minWidth: 0,
    },
    pendingUploadName: {
      color: colors.text,
      fontFamily: fonts.medium,
      fontSize: 13,
    },
    pendingUploadSize: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 11,
      marginTop: 2,
    },
    uploadProgressWrap: {
      marginTop: hp(1),
      gap: 6,
    },
    uploadProgressTrack: {
      height: 6,
      borderRadius: 999,
      backgroundColor: isDark ? colors.border : '#E2E8F0',
      overflow: 'hidden',
    },
    uploadProgressFill: {
      height: '100%',
      borderRadius: 999,
      backgroundColor: accent,
    },
    uploadProgressText: {
      color: colors.gray,
      fontFamily: fonts.medium,
      fontSize: 11,
      textAlign: 'center',
    },
    uploadSubmitBtn: {
      marginTop: hp(1),
      borderRadius: 10,
      backgroundColor: accent,
      alignItems: 'center',
      paddingVertical: hp(1.2),
    },
    uploadSubmitText: {
      color: colors.white,
      fontFamily: fonts.semibold,
      fontSize: 13,
    },
    attachmentPreviewBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.92)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    attachmentPreviewClose: {
      position: 'absolute',
      top: hp(6),
      right: wp(5),
      zIndex: 2,
      padding: wp(2),
    },
    attachmentPreviewImage: {
      width: '92%',
      height: '72%',
    },
    attachmentPreviewCaption: {
      color: colors.white,
      fontFamily: fonts.medium,
      fontSize: 13,
      marginTop: hp(1.5),
      paddingHorizontal: wp(6),
      textAlign: 'center',
    },
    attachmentIconWrap: {
      width: wp(10),
      height: wp(10),
      borderRadius: 12,
      backgroundColor: isDark ? `${accent}18` : `${accent}08`,
      alignItems: 'center',
      justifyContent: 'center',
    },
    attachmentMeta: {
      flex: 1,
    },
    attachmentName: {
      color: colors.text,
      fontFamily: fonts.semibold,
      fontSize: 14,
    },
    attachmentDate: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 11,
      marginTop: 3,
    },
    listCard: {
      backgroundColor: panelBg,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: isDark ? colors.border : '#E2E8F0',
      padding: wp(4),
      marginBottom: hp(1.1),
      ...softShadow,
    },
    listCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: hp(0.6),
      gap: 8,
    },
    listCardTitle: {
      color: titleColor,
      fontFamily: fonts.semibold,
      fontSize: 15,
      flex: 1,
      letterSpacing: -0.2,
    },
    listCardMeta: {
      color: mutedText,
      fontFamily: fonts.regular,
      fontSize: 12,
      marginTop: 2,
    },
    listCardBody: {
      color: mutedText,
      fontFamily: fonts.regular,
      fontSize: 13,
      lineHeight: 20,
      marginTop: hp(0.6),
    },
    statusBadge: {
      paddingHorizontal: 9,
      paddingVertical: 4,
      borderRadius: 8,
      backgroundColor: isDark ? `${accent}22` : `${accent}08`,
      borderWidth: 1,
      borderColor: isDark ? `${accent}33` : `${accent}18`,
    },
    statusBadgeText: {
      color: accent,
      fontFamily: fonts.bold,
      fontSize: 9,
      letterSpacing: 0.6,
    },
    statusBadgeMuted: {
      backgroundColor: isDark ? colors.inputBg : '#F1F5F9',
      borderColor: fieldBorder,
    },
    statusBadgeTextMuted: {
      color: mutedText,
    },
    callIconWrap: {
      width: wp(10.5),
      height: wp(10.5),
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: wp(2.5),
      overflow: 'hidden',
    },
    listCardRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    listCardContent: {
      flex: 1,
    },
    commentBox: {
      backgroundColor: fieldBg,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: fieldBorder,
      paddingHorizontal: wp(3.8),
      paddingVertical: hp(1.5),
      minHeight: hp(10),
    },
    commentText: {
      color: titleColor,
      fontFamily: fonts.regular,
      fontSize: 14,
      lineHeight: 23,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(15,23,42,0.55)',
      justifyContent: 'flex-end',
    },
    modalSheet: {
      backgroundColor: panelBg,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: wp(5),
      paddingTop: hp(1.2),
      paddingBottom: hp(4),
      maxHeight: '75%',
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: -4 },
          shadowOpacity: 0.12,
          shadowRadius: 16,
        },
        android: { elevation: 12 },
      }),
    },
    modalHandle: {
      width: wp(12),
      height: 4,
      borderRadius: 2,
      backgroundColor: isDark ? colors.border : '#CBD5E1',
      alignSelf: 'center',
      marginBottom: hp(1.8),
    },
    modalTitle: {
      color: titleColor,
      fontFamily: fonts.bold,
      fontSize: 18,
      letterSpacing: -0.3,
      marginBottom: hp(1.5),
    },
    modalInput: {
      backgroundColor: fieldBg,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: fieldBorder,
      paddingHorizontal: wp(3.8),
      paddingVertical: hp(1.3),
      color: colors.text,
      fontFamily: fonts.regular,
      fontSize: 14,
      minHeight: hp(12),
      textAlignVertical: 'top',
      lineHeight: 22,
    },
    modalActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 12,
      marginTop: hp(2),
    },
    modalCancelBtn: {
      paddingVertical: hp(1.2),
      paddingHorizontal: padH,
      borderRadius: 10,
    },
    modalCancelText: {
      color: mutedText,
      fontFamily: fonts.semibold,
      fontSize: 14,
    },
    modalSaveBtn: {
      borderRadius: 12,
      paddingVertical: hp(1.25),
      paddingHorizontal: wp(5),
      minWidth: wp(24),
      alignItems: 'center',
      overflow: 'hidden',
    },
    modalSaveText: {
      color: colors.white,
      fontFamily: fonts.semibold,
      fontSize: 14,
    },
    placeholder: {
      color: mutedText,
      fontFamily: fonts.regular,
      marginTop: hp(2),
      textAlign: 'center',
    },
    listCardChevron: {
      marginTop: 4,
    },
    modalBackdropFlex: {
      flex: 1,
    },
    modalLoader: {
      marginVertical: hp(2),
    },
    modalBodyScroll: {
      maxHeight: hp(30),
    },
  })
}
