import { StyleSheet, Platform } from 'react-native'
import {
  wp,
  hp,
  normalizeStyleOptions,
  getContentMaxWidth,
  screenPadding,
} from '../../../theme/layout'
import { bodyFontSize, touchTarget } from '../../../theme/tokens'
import { fonts } from '../../../constant'

export const getStyles = (colors, isDark = false, options = {}) => {
  const {
    isCompact = false,
    isWide = false,
  } = normalizeStyleOptions(options)

  const padH = screenPadding(isWide, isCompact)
  const contentMaxWidth = getContentMaxWidth(isWide)
  const bubbleMaxWidth = isWide ? '62%' : isCompact ? '84%' : '78%'
  const messageImageWidth = isWide ? wp(48) : isCompact ? wp(30) : wp(30)
  const actionBtnSize = touchTarget(isCompact)
  const msgFontSize = bodyFontSize(isCompact)
  const headerBtnSize = isCompact ? wp(9) : wp(10)

  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.appBg || colors.dark,
    alignItems: isWide ? 'center' : 'stretch',
  },
  chatShell: {
    flex: 1,
    width: '100%',
    maxWidth: contentMaxWidth,
  },
  headerWrap: {
    zIndex: 20,
    elevation: 8,
    backgroundColor: colors.headerBg || colors.appBg || colors.dark,
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: hp(1),
    justifyContent: 'space-between',
    minHeight: hp(7),
  },
  headerLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(1.5),
    paddingLeft: wp(2),
    minWidth: 0,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(1.2),
    paddingRight: wp(2.5),
    flexShrink: 0,
  },
  headerActionBtn: {
    padding: wp(0.5),
  },
  headerActionIcon: {
    width: wp(4.8),
    height: wp(4.8),
    tintColor: colors.text,
  },
  searchHeader: {
    paddingRight: wp(3),
  },
  searchInputWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: wp(3),
    minHeight: wp(10),
  },
  searchInput: {
    flex: 1,
    color: colors.text,
    fontFamily: fonts.regular,
    fontSize: 14,
    paddingVertical: wp(2),
  },
  searchClearBtn: {
    marginLeft: wp(1),
  },
  headerBtn: {
    width: headerBtnSize,
    height: headerBtnSize,
    borderRadius: headerBtnSize / 2,
    backgroundColor: isDark ? 'rgba(255,255,255,0.08)' : (colors.cardBg || 'rgba(255,255,255,0.92)'),
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: isDark ? 'rgba(255,255,255,0.12)' : colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: wp(1.5),
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: isDark ? 0.2 : 0.08,
        shadowRadius: 4,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  backArrow: {
    color: colors.text,
    fontSize: 24,
  },
  headerAvatar: {
    width: wp(9),
    height: wp(9),
    borderRadius: wp(4.5),
    marginRight: 10,
  },
  headerCenter: {
    flex: 1,
    minWidth: 0,
    paddingRight: wp(1),
  },
  headerName: {
    color: colors.text,
    fontFamily: fonts.semibold,
    fontSize: 15,
    lineHeight: 20,
  },
  headerPhone: {
    color: colors.gray,
    fontFamily: fonts.regular,
    fontSize: 11,
    marginTop: 1,
  },
  assignBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: wp(1.5),
    paddingRight: wp(1.2),
    paddingVertical: hp(0.55),
    borderRadius: 999,
    backgroundColor: isDark ? colors.cardBg : (colors.white || colors.cardBg),
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: isDark ? 'rgba(255,255,255,0.12)' : `${colors.border}99`,
    gap: wp(1.2),
    maxWidth: wp(36),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: isDark ? 0.2 : 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  assignBadgeWrap: {
    marginRight: wp(0.3),
    flexShrink: 1,
    minWidth: 0,
  },
  assignModalRoot: {
    flex: 1,
  },
  assignModalOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.08)',
  },
  assignDropdownModal: {
    position: 'absolute',
    minWidth: wp(52),
    maxWidth: wp(70),
    backgroundColor: isDark ? colors.cardBg : (colors.white || colors.cardBg),
    borderRadius: 10,
    borderWidth: 1,
    borderColor: isDark ? colors.surfaceBorder || colors.border : colors.border,
    paddingVertical: hp(0.4),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: isDark ? 0.35 : 0.18,
    shadowRadius: 12,
    elevation: 24,
  },
  assignEditBtn: {
    width: wp(6.2),
    height: wp(6.2),
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: colors.primary,
    backgroundColor: isDark ? colors.cardBg : (colors.white || colors.cardBg),
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: wp(0.5),
  },
  assignDropdownItem: {
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.1),
  },
  assignDropdownItemHighlight: {
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  assignDropdownText: {
    color: isDark ? colors.headerText || colors.text : colors.text,
    fontFamily: fonts.regular,
    fontSize: 14,
  },
  assignDropdownLoading: {
    paddingVertical: hp(2),
    alignItems: 'center',
  },
  assignDropdownEmpty: {
    color: colors.gray,
    fontFamily: fonts.regular,
    fontSize: 13,
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.2),
  },
  assignAvatar: {
    width: wp(5.2),
    height: wp(5.2),
    borderRadius: wp(2.6),
    backgroundColor: `${colors.primary}33`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  assignAvatarBot: {
    backgroundColor: '#E53935',
  },
  assignAvatarHuman: {
    backgroundColor: colors.primary,
  },
  assignAvatarText: {
    fontFamily: fonts.bold,
    fontSize: 10,
  },
  assignAvatarTextBot: {
    color: '#111111',
  },
  assignAvatarTextHuman: {
    color: colors.white,
  },
  assignBadgeText: {
    flexShrink: 1,
    color: isDark ? colors.headerText || colors.text : colors.text,
    fontFamily: fonts.medium,
    fontSize: 11,
  },
  headerIcon: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.border,
    marginLeft: 8,
  },
  infoBtn: {
    backgroundColor: `${colors.orange}22`,
    borderWidth: 1,
    borderColor: `${colors.orange}44`,
  },
  infoTxt: {
    color: colors.white,
    fontFamily: fonts.medium,
    fontSize: 12,
  },

  chatBody: {
    flex: 1,
    zIndex: 0,
    minHeight: 0,
  },
  messageList: {
    flex: 1,
    minHeight: 0,
  },
  listContent: {
    paddingHorizontal: padH,
    paddingTop: hp(0.5),
    paddingBottom: hp(1.5),
  },
  listTopSpacer: {
    flexGrow: 1,
  },
  messageItem: {
    flexGrow: 0,
    flexShrink: 0,
  },
  listContentPinned: {
    flexGrow: 1,
  },
  listContentSearch: {
    justifyContent: 'flex-start',
  },
  searchResultsHeader: {
    paddingVertical: hp(1),
    alignItems: 'center',
  },
  searchResultsText: {
    color: colors.gray,
    fontFamily: fonts.medium,
    fontSize: 12,
  },
  row: {
    width: '100%',
    marginVertical: 6,
    flexDirection: 'row',
    flexGrow: 0,
    flexShrink: 0,
  },
  rowLeft: {
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  rowRight: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  rowCenter: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  bubble: {
    maxWidth: bubbleMaxWidth,
    paddingHorizontal: isCompact ? 12 : 14,
    paddingVertical: isCompact ? 8 : 10,
    borderRadius: 12,
    flexGrow: 0,
    flexShrink: 0,
  },
  bubbleAttachmentOnly: {
    paddingVertical: isCompact ? 6 : 8,
  },
  bubbleLeft: {
    backgroundColor: colors.inputBg,
    borderTopLeftRadius: 0,
    borderWidth: 1,
    borderColor: colors.border,
    alignSelf: 'flex-start',
  },
  bubbleRight: {
    backgroundColor: colors.primary,
    borderTopRightRadius: 0,
    alignSelf: 'flex-end',
  },
  bubbleStandaloneLeft: {
    borderTopLeftRadius: 12,
  },
  bubbleStandaloneRight: {
    borderTopRightRadius: 12,
  },
  msgText: {
    color: colors.text,
    fontFamily: fonts.regular,
    fontSize: 16,
    lineHeight: 22,
  },
  msgTextRight: {
    color: colors.white,
  },
  msgFormattedBlock: {
    marginTop: 8,
  },
  msgFormattedListItem: {
    marginTop: 2,
  },
  systemBubble: {
    borderRadius: wp(5),
    justifyContent: 'center',
    alignItems: 'center',
  },
  systemText: {
    color: colors.text,
    fontFamily: fonts.regular,
    fontSize: 12,
    paddingHorizontal: wp(2),
    paddingTop: hp(0.5),
    paddingBottom: hp(0.2),
    textAlign: 'center',
  },
  systemMetaInline: {
    color: colors.gray,
    fontFamily: fonts.regular,
    fontSize: 10,
  },
  systemMetaText: {
    color: colors.gray,
    fontFamily: fonts.regular,
    fontSize: 10,
    paddingHorizontal: wp(2),
    paddingBottom: hp(0.5),
    textAlign: 'center',
  },
  systemPill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    maxWidth: isWide ? '88%' : '94%',
    marginVertical: hp(0.45),
    paddingVertical: hp(0.75),
    paddingHorizontal: wp(3.2),
    borderRadius: 999,
    backgroundColor: isDark ? `${colors.primary}14` : colors.white || colors.cardBg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: `${colors.primary}35`,
    gap: wp(2.2),
    ...Platform.select({
      ios: {
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: isDark ? 0.22 : 0.1,
        shadowRadius: 8,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  systemPillStacked: {
    alignItems: 'flex-start',
    borderRadius: wp(4.8),
    paddingVertical: hp(1),
  },
  systemPillIconWrap: {
    width: wp(7.2),
    height: wp(7.2),
    borderRadius: wp(3.6),
    backgroundColor: `${colors.primary}14`,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: `${colors.primary}28`,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  systemPillContent: {
    flexShrink: 1,
    justifyContent: 'center',
  },
  systemPillText: {
    color: colors.text,
    fontFamily: fonts.medium,
    fontSize: isCompact ? 11.5 : 12.5,
    letterSpacing: 0.2,
    lineHeight: isCompact ? 17 : 19,
    flexShrink: 1,
  },
  systemPillLabel: {
    color: colors.gray,
    fontFamily: fonts.regular,
    fontSize: isCompact ? 11.5 : 12.5,
    letterSpacing: 0.15,
  },
  systemPillName: {
    color: colors.primary,
    fontFamily: fonts.semibold,
    fontSize: isCompact ? 11.5 : 12.5,
    letterSpacing: 0.1,
  },
  systemPillMetaInline: {
    color: colors.gray,
    fontFamily: fonts.regular,
    fontSize: isCompact ? 10 : 10.5,
    letterSpacing: 0.12,
  },
  systemPillMetaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: wp(1),
    marginTop: hp(0.4),
    paddingHorizontal: wp(2.2),
    paddingVertical: hp(0.28),
    borderRadius: 999,
    backgroundColor: isDark ? `${colors.primary}18` : `${colors.primary}10`,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: `${colors.primary}20`,
  },
  systemPillMeta: {
    color: colors.gray,
    fontFamily: fonts.medium,
    fontSize: isCompact ? 10 : 10.5,
    letterSpacing: 0.15,
  },
  metaRow: {
    alignItems: 'flex-end',
  },
  timeText: {
    color: colors.gray,
    fontSize: 10,
    fontFamily: fonts.regular,
  },
  timeTextRight: {
    color: colors.white,
    opacity: 0.8,
  },
  tickText: {
    color: colors.white,
    fontSize: 10,
    fontFamily: fonts.medium,
    opacity: 0.7,
  },
  tickSeen: {
    opacity: 1,
  },
  messageFilesWrap: {
    gap: 8,
    marginBottom: 4,
    alignSelf: 'flex-start',
    maxWidth: '100%',
  },
  messageImageWrap: {
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: colors.inputBg,
    width: messageImageWidth,
    maxWidth: '100%',
    height: isCompact ? hp(18) : hp(22),
    maxHeight: 300,
    alignSelf: 'flex-start',
    flexGrow: 0,
    flexShrink: 0,
  },
  messageImage: {
    width: messageImageWidth,
    maxWidth: '100%',
    height: isCompact ? hp(18) : hp(22),
    maxHeight: 300,
    borderRadius: 10,
    flexGrow: 0,
    flexShrink: 0,
  },
  messageFileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2.2),
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: `${colors.primary}10`,
    borderWidth: 1,
    borderColor: `${colors.primary}22`,
    alignSelf: 'flex-start',
    maxWidth: '100%',
  },
  messageFileCardLeft: {
    backgroundColor: colors.inputBg,
    borderColor: colors.border,
  },
  messageFileCardRight: {
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderColor: 'rgba(255,255,255,0.22)',
  },
  messageFileCardCompact: {
    width: messageImageWidth,
    maxWidth: '100%',
    minHeight: wp(11),
    maxHeight: wp(13),
    paddingVertical: 6,
    flexGrow: 0,
    flexShrink: 0,
  },
  messageFileMetaSpacer: {
    flex: 1,
    minWidth: 0,
  },
  messageFileIconWrap: {
    width: wp(10),
    height: wp(10),
    borderRadius: 10,
    backgroundColor: `${colors.primary}16`,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  messageFileIconWrapRight: {
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  messageFileMeta: {
    flex: 1,
    minWidth: 0,
    flexShrink: 1,
  },
  messageFileName: {
    color: colors.text,
    fontFamily: fonts.semibold,
    fontSize: 13,
    lineHeight: 18,
  },
  messageFileNameRight: {
    color: colors.white,
  },
  messageFileSubtext: {
    color: colors.gray,
    fontFamily: fonts.regular,
    fontSize: 11,
    marginTop: 2,
  },
  messageFileSubtextRight: {
    color: colors.white,
    opacity: 0.78,
  },
  pendingFileWrap: {
    paddingHorizontal: padH,
    paddingTop: hp(0.8),
    backgroundColor: colors.cardBg,
  },
  pendingFileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2.5),
    padding: wp(2.5),
    borderRadius: 12,
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: `${colors.primary}30`,
  },
  pendingFileThumb: {
    width: wp(14),
    height: wp(14),
    borderRadius: 10,
    backgroundColor: colors.border,
  },
  pendingFileIconBox: {
    width: wp(14),
    height: wp(14),
    borderRadius: 10,
    backgroundColor: `${colors.primary}14`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingFileMeta: {
    flex: 1,
    minWidth: 0,
  },
  pendingFileName: {
    color: colors.text,
    fontFamily: fonts.semibold,
    fontSize: 13,
  },
  pendingFileHint: {
    color: colors.gray,
    fontFamily: fonts.regular,
    fontSize: 11,
    marginTop: 2,
  },
  pendingFileRemoveBtn: {
    padding: wp(0.5),
  },
  imagePreviewBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imagePreviewClose: {
    position: 'absolute',
    top: hp(6),
    right: wp(5),
    zIndex: 2,
    padding: wp(2),
  },
  imagePreviewImage: {
    width: '92%',
    height: '72%',
  },
  imagePreviewCaption: {
    color: colors.white,
    fontFamily: fonts.medium,
    fontSize: 13,
    marginTop: hp(1.5),
    paddingHorizontal: wp(6),
    textAlign: 'center',
  },
  sendBtnDisabled: {
    opacity: 0.45,
  },

  inputFooter: {
    backgroundColor: colors.cardBg,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    zIndex: 2,
    elevation: 4,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: padH,
    paddingTop: hp(0.8),
    backgroundColor: colors.cardBg,
  },
  botHandlingBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: padH,
    marginTop: hp(1.2),
    paddingVertical: hp(1.4),
    paddingHorizontal: wp(4),
    borderRadius: 12,
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  botHandlingLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2),
    marginRight: wp(2),
  },
  botHandlingText: {
    flex: 1,
    color: colors.text,
    fontFamily: fonts.medium,
    fontSize: 13,
  },
  attachBtn: {
    width: actionBtnSize,
    height: actionBtnSize,
    marginRight: wp(2),
    marginBottom: hp(0.15),
    borderRadius: actionBtnSize / 2,
    backgroundColor: `${colors.primary}12`,
    borderWidth: 1,
    borderColor: `${colors.primary}30`,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    // elevation: 2,
  },
  attachBtnDisabled: {
    opacity: 0.55,
  },
  input: {
    flex: 1,
    backgroundColor: colors.inputBg,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingTop: Platform.OS === 'ios' ? 10 : 8,
    paddingBottom: Platform.OS === 'ios' ? 10 : 8,
    minHeight: actionBtnSize,
    maxHeight: hp(14),
    color: colors.text,
    fontFamily: fonts.regular,
    fontSize: 14,
    lineHeight: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sendBtn: {
    width: actionBtnSize,
    height: actionBtnSize,
    marginLeft: 10,
    marginBottom: hp(0.15),
    borderRadius: actionBtnSize / 2,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendArrow: {
    color: colors.white,
    fontSize: 25,
    marginLeft: 2,
  },
  dncIconWrap: {
    width: wp(7),
    height: wp(7),
    borderRadius: wp(3.5),
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  dncstatusContainer: {
    backgroundColor: colors.white,
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.5),
    borderRadius: wp(5),
    marginRight: wp(2),
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(1),
  },
  dncstatusText: {
    color: colors.red,
    fontFamily: fonts.medium,
    fontSize: 10,
  },
  botCallBarWrap: {
    backgroundColor: `${colors.primary}14`,
    paddingVertical: hp(0.55),
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: `${colors.primary}22`,
  },
  botCallBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(2.5),
    paddingVertical: hp(0.35),
    borderRadius: 999,
    backgroundColor: `${colors.primary}18`,
    gap: wp(2),
    maxWidth: wp(92),
  },
  botCallIconBtn: {
    width: wp(9),
    height: wp(9),
    borderRadius: wp(4.5),
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  botCallActiveBtn: {
    backgroundColor: `${colors.primary}22`,
    borderWidth: 1,
    borderColor: `${colors.primary}44`,
  },
  botCallHangupBtn: {
    backgroundColor: colors.danger || '#E53935',
  },
  botCallStatusPill: {
    paddingHorizontal: wp(3.5),
    paddingVertical: hp(0.55),
    borderRadius: 999,
    backgroundColor: `${colors.primary}22`,
    flexShrink: 0,
  },
  botCallStatusText: {
    color: colors.primary,
    fontFamily: fonts.semibold,
    fontSize: 12,
    letterSpacing: 0.2,
  },
  botCallDismissBtn: {
    paddingHorizontal: wp(1),
    paddingVertical: hp(0.3),
    marginLeft: 'auto',
  },
  loadingSkeleton: {
    paddingHorizontal: wp(4),
    flex: 1,
  },
  listEmptyWrap: {
    paddingTop: hp(4),
    alignItems: 'center',
  },
  listLoadEarlier: {
    alignSelf: 'center',
    paddingVertical: hp(1.2),
    paddingHorizontal: wp(4),
    marginBottom: hp(1),
  },
  listLoadEarlierText: {
    color: colors.primary,
    fontFamily: fonts.semibold,
    fontSize: 13,
  },
  listEmptyText: {
    color: colors.gray,
    fontSize: 14,
    fontFamily: fonts.regular,
    textAlign: 'center',
    paddingHorizontal: wp(6),
  },
  headerStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
  },
  headerStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  headerPhoneInline: {
    color: colors.gray,
    fontFamily: fonts.regular,
    fontSize: 11,
    marginTop: 0,
  },
  })
}

export default getStyles
