import { StyleSheet, Platform } from 'react-native'
import { fonts } from '../../constant'
import { wp, hp, getModalLayout, getContentMaxWidth } from '../../theme/layout'

export { getModalLayout }

export const getEditOrgModalStyles = (colors, isDark = false, options = {}) => {
  const { isCompact = false, isWide = false, bottomInset = 0 } = options
  const sheetMaxWidth = isWide ? getContentMaxWidth(true, 480) : undefined

  return StyleSheet.create({
    backdrop: {
      flex: 1,
      justifyContent: isWide ? 'center' : 'flex-end',
      alignItems: isWide ? 'center' : 'stretch',
      backgroundColor: 'rgba(15, 23, 42, 0.55)',
      paddingHorizontal: isWide ? wp(4) : 0,
    },
    backdropTap: {
      ...StyleSheet.absoluteFillObject,
    },
    sheetWrap: {
      width: isWide ? sheetMaxWidth : '100%',
      maxWidth: sheetMaxWidth,
      zIndex: 1,
    },
    sheet: {
      backgroundColor: colors.cardBg,
      borderTopLeftRadius: isWide ? wp(4) : wp(6),
      borderTopRightRadius: isWide ? wp(4) : wp(6),
      borderBottomLeftRadius: isWide ? wp(4) : 0,
      borderBottomRightRadius: isWide ? wp(4) : 0,
      paddingBottom: Math.max(isCompact ? hp(2.5) : hp(3), bottomInset + hp(1)),
      borderWidth: StyleSheet.hairlineWidth,
      borderBottomWidth: isWide ? StyleSheet.hairlineWidth : 0,
      borderColor: colors.surfaceBorder || colors.border,
      maxHeight: hp(92),
      ...Platform.select({
        ios: {
          shadowColor: '#0F172A',
          shadowOffset: { width: 0, height: isWide ? 8 : -4 },
          shadowOpacity: isDark ? 0.35 : 0.12,
          shadowRadius: isWide ? 24 : 16,
        },
        android: {
          elevation: 12,
        },
      }),
    },
    handle: {
      alignSelf: 'center',
      width: isCompact ? wp(9) : wp(10),
      height: hp(0.5),
      borderRadius: hp(0.25),
      backgroundColor: isDark ? 'rgba(255,255,255,0.2)' : 'rgba(0,0,0,0.12)',
      marginTop: hp(1.2),
      marginBottom: hp(0.75),
      display: isWide ? 'none' : 'flex',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: wp(5),
      paddingTop: isWide ? hp(2) : hp(1),
      paddingBottom: hp(0.5),
    },
    headerTitle: {
      color: colors.appText || colors.text,
      fontFamily: fonts.bold,
      fontSize: isCompact ? wp(4.5) : wp(5),
      letterSpacing: 0.2,
    },
    headerSubtitle: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: isCompact ? wp(3.1) : wp(3.3),
      lineHeight: isCompact ? hp(2.2) : hp(2.4),
      paddingHorizontal: wp(5),
      marginBottom: isCompact ? hp(1.6) : hp(2),
    },
    closeBtn: {
      height: isCompact ? wp(8.5) : wp(9),
      width: isCompact ? wp(8.5) : wp(9),
      borderRadius: isCompact ? wp(4.25) : wp(4.5),
      backgroundColor: isDark ? 'rgba(255,255,255,0.08)' : colors.inputBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    closeBtnPressed: {
      opacity: 0.7,
    },
    bodyScroll: {
      maxHeight: isWide ? hp(58) : hp(52),
    },
    body: {
      paddingHorizontal: wp(5),
      paddingBottom: hp(0.5),
    },
    sectionLabel: {
      color: colors.gray,
      fontSize: 11,
      fontFamily: fonts.semibold,
      textTransform: 'uppercase',
      letterSpacing: 1.1,
      marginBottom: hp(1.2),
      marginTop: hp(0.4),
    },
    inputGroup: {
      marginBottom: isCompact ? hp(1.4) : hp(1.8),
    },
    label: {
      color: colors.appText || colors.text,
      fontFamily: fonts.medium,
      fontSize: isCompact ? wp(3.1) : wp(3.3),
      marginBottom: hp(0.8),
      opacity: 0.9,
    },
    inputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : colors.inputBg,
      borderRadius: isCompact ? wp(3.2) : wp(3.5),
      minHeight: isCompact ? hp(5.8) : hp(6.2),
      paddingHorizontal: isCompact ? wp(3.2) : wp(3.5),
    },
    inputWrapMultiline: {
      alignItems: 'flex-start',
      paddingVertical: hp(1.2),
      minHeight: hp(10),
    },
    inputIcon: {
      marginRight: wp(2.5),
      marginTop: 2,
    },
    input: {
      flex: 1,
      color: colors.text,
      fontFamily: fonts.regular,
      fontSize: isCompact ? wp(3.6) : wp(3.8),
      paddingVertical: hp(1.2),
    },
    inputMultiline: {
      minHeight: hp(8),
      textAlignVertical: 'top',
      paddingTop: 0,
    },
    hoursCard: {
      backgroundColor: isDark ? 'rgba(255,255,255,0.03)' : colors.inputBg,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      paddingHorizontal: wp(3.5),
      paddingVertical: hp(0.6),
      marginBottom: hp(1.6),
    },
    bhRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: hp(1.1),
    },
    bhRowDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.surfaceBorder || colors.border,
    },
    bhDay: {
      color: colors.appText || colors.text,
      fontFamily: fonts.medium,
      fontSize: 13,
      width: wp(24),
    },
    bhValueWrap: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: wp(2),
    },
    bhBox: {
      flex: 1,
      backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : colors.cardBg,
      paddingVertical: hp(0.9),
      paddingHorizontal: wp(2.5),
      borderRadius: 10,
      alignItems: 'center',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
    },
    bhBoxText: {
      color: colors.text,
      fontFamily: fonts.medium,
      fontSize: 12,
    },
    bhBoxTextClosed: {
      color: colors.gray,
      fontStyle: 'italic',
    },
    selectBtn: {
      backgroundColor: isDark ? `${colors.primary}22` : `${colors.primary}12`,
      paddingVertical: hp(0.9),
      paddingHorizontal: wp(2.8),
      borderRadius: 10,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: `${colors.primary}35`,
    },
    selectTxt: {
      color: colors.primary,
      fontFamily: fonts.semibold,
      fontSize: 11,
      letterSpacing: 0.2,
    },
    footer: {
      flexDirection: isCompact ? 'column' : 'row',
      gap: isCompact ? hp(1.2) : wp(3),
      paddingHorizontal: wp(5),
      paddingTop: hp(1.2),
      marginTop: hp(0.5),
    },
    cta: {
      flex: isCompact ? undefined : 1,
      width: isCompact ? '100%' : undefined,
      height: isCompact ? hp(5.8) : hp(6.2),
      borderRadius: isCompact ? wp(3.2) : wp(3.5),
      alignItems: 'center',
      justifyContent: 'center',
    },
    ctaPressed: {
      opacity: 0.88,
    },
    cancel: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : colors.cardBg,
    },
    saveWrap: {
      flex: isCompact ? undefined : 1,
      width: isCompact ? '100%' : undefined,
      borderRadius: isCompact ? wp(3.2) : wp(3.5),
      overflow: 'hidden',
    },
    save: {
      width: '100%',
    },
    cancelText: {
      color: colors.text,
      fontFamily: fonts.semibold,
      fontSize: isCompact ? wp(3.6) : wp(3.8),
    },
    saveText: {
      color: colors.white,
      fontFamily: fonts.semibold,
      fontSize: isCompact ? wp(3.6) : wp(3.8),
      letterSpacing: 0.2,
    },

    pickerBackdrop: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(15, 23, 42, 0.6)',
      paddingHorizontal: wp(5),
    },
    pickerCard: {
      width: '100%',
      maxWidth: 420,
      backgroundColor: colors.cardBg,
      borderRadius: 18,
      padding: wp(4.5),
      maxHeight: hp(75),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      ...Platform.select({
        ios: {
          shadowColor: '#0F172A',
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: isDark ? 0.35 : 0.12,
          shadowRadius: 20,
        },
        android: {
          elevation: 10,
        },
      }),
    },
    pickerHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: hp(1.4),
    },
    pickerTitle: {
      color: colors.appText || colors.text,
      fontFamily: fonts.bold,
      fontSize: 17,
      letterSpacing: 0.2,
    },
    pickerSubtitle: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 12,
      marginBottom: hp(1.4),
    },
    optionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : colors.inputBg,
      borderRadius: 12,
      paddingVertical: hp(1.4),
      paddingHorizontal: wp(3.5),
      marginBottom: hp(0.8),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
    },
    optionRowSelected: {
      borderColor: `${colors.primary}55`,
      backgroundColor: isDark ? `${colors.primary}14` : `${colors.primary}08`,
    },
    optionText: {
      color: colors.appText || colors.text,
      fontFamily: fonts.medium,
      fontSize: 14,
    },
    optionRight: {
      color: colors.primary,
      fontFamily: fonts.semibold,
      fontSize: 11,
      letterSpacing: 0.3,
      textTransform: 'uppercase',
    },
    optionRightMuted: {
      color: colors.gray,
      fontFamily: fonts.medium,
      fontSize: 11,
      textTransform: 'none',
    },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.surfaceBorder || colors.border,
      marginVertical: hp(1.2),
    },
    customHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: hp(1),
    },
    optionSection: {
      color: colors.appText || colors.text,
      fontFamily: fonts.semibold,
      fontSize: 13,
    },
    checkboxSquare: {
      width: 20,
      height: 20,
      borderRadius: 6,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : colors.cardBg,
    },
    checkboxSquareChecked: {
      backgroundColor: `${colors.primary}18`,
      borderColor: colors.primary,
    },
    checkboxDot: {
      width: 10,
      height: 10,
      backgroundColor: colors.primary,
      borderRadius: 3,
    },
    fieldRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: wp(2.5),
    },
    fieldCol: {
      flex: 1,
    },
    fieldLabel: {
      color: colors.gray,
      fontFamily: fonts.medium,
      fontSize: 11,
      marginBottom: hp(0.7),
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    textField: {
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : colors.inputBg,
      color: colors.text,
      borderRadius: 12,
      paddingVertical: hp(1.3),
      paddingHorizontal: wp(3),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      fontFamily: fonts.regular,
      fontSize: 14,
    },
    pickerFooter: {
      flexDirection: 'row',
      gap: wp(3),
      marginTop: hp(1.6),
    },
  })
}
