import { StyleSheet } from 'react-native'
import { fonts } from '../../../constant'
import {
  wp,
  hp,
  screenPadding,
  getScrollBottomPadding,
  getContentMaxWidth,
  normalizeStyleOptions,
} from '../../../theme/layout'
import { cardShadow } from '../../../theme/shadows'

export { cardShadow }

export function createSettingsScreenStyles(colors, isDark = false, options = {}) {
  const {
    bottomInset = 0,
    isCompact = false,
    isWide = false,
  } = normalizeStyleOptions(options)

  const padH = screenPadding(isWide, isCompact)
  const contentMaxWidth = getContentMaxWidth(isWide)
  const scrollBottom = getScrollBottomPadding(bottomInset, hp(14))

  return {
    container: {
      flex: 1,
      backgroundColor: colors.appBg || colors.dark,
    },
    content: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: padH,
      paddingTop: hp(1),
      paddingBottom: scrollBottom,
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: isWide ? 'center' : 'stretch',
    },
    listContent: {
      paddingHorizontal: padH,
      paddingTop: hp(1),
      paddingBottom: scrollBottom,
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: isWide ? 'center' : 'stretch',
    },
    heroCard: {
      backgroundColor: colors.cardBg,
      borderRadius: 18,
      marginBottom: hp(2),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? `${colors.primary}35` : `${colors.primary}20`,
      overflow: 'hidden',
      ...cardShadow(isDark),
    },
    heroGradient: {
      ...StyleSheet.absoluteFillObject,
    },
    heroContent: {
      paddingHorizontal: wp(5),
      paddingVertical: hp(2.4),
    },
    heroIconWrap: {
      marginBottom: hp(1.4),
    },
    heroIcon: {
      width: 44,
      height: 44,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroTitle: {
      color: colors.appText || colors.text,
      fontSize: 20,
      fontFamily: fonts.bold,
      letterSpacing: 0.2,
      marginBottom: 6,
    },
    heroSubtitle: {
      color: colors.gray,
      fontSize: 13,
      fontFamily: fonts.regular,
      lineHeight: 20,
    },
    heroActionBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'stretch',
      width: '100%',
      paddingHorizontal: 20,
      minHeight: hp(5.2),
      paddingVertical: hp(1.4),
      borderRadius: 12,
      gap: 8,
      marginTop: hp(1.6),
    },
    heroActionBtnText: {
      color: colors.white,
      fontFamily: fonts.semibold,
      fontSize: 14,
      letterSpacing: 0.2,
      flexShrink: 0,
      includeFontPadding: false,
    },
    statsRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: hp(2.2),
    },
    statPill: {
      flex: 1,
      backgroundColor: colors.cardBg,
      borderRadius: 14,
      paddingVertical: hp(1.4),
      paddingHorizontal: wp(3.5),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      ...cardShadow(isDark),
    },
    statPillValue: {
      color: colors.appText || colors.text,
      fontFamily: fonts.bold,
      fontSize: 18,
      marginBottom: 2,
    },
    statPillLabel: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 11,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    sectionLabel: {
      color: colors.gray,
      fontSize: 11,
      fontFamily: fonts.semibold,
      textTransform: 'uppercase',
      letterSpacing: 1.2,
      marginBottom: hp(1),
      marginLeft: wp(1),
    },
    card: {
      backgroundColor: colors.cardBg,
      borderRadius: 16,
      padding: wp(4),
      marginBottom: hp(1.5),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      ...cardShadow(isDark),
    },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.surfaceBorder || colors.border,
      marginBottom: hp(1.4),
    },
    metaChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: hp(1.2),
    },
    metaChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : colors.inputBg,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 10,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
    },
    metaChipText: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 11,
    },
    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.cardBg,
      borderRadius: 16,
      paddingVertical: hp(4),
      paddingHorizontal: wp(8),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      borderStyle: 'dashed',
      marginBottom: hp(2),
    },
    emptyIcon: {
      width: 52,
      height: 52,
      borderRadius: 26,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : colors.inputBg,
      marginBottom: hp(1.4),
    },
    emptyTitle: {
      color: colors.appText || colors.text,
      fontFamily: fonts.semibold,
      fontSize: 15,
      marginBottom: 6,
      textAlign: 'center',
    },
    emptyHint: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 13,
      textAlign: 'center',
      lineHeight: 19,
    },
    stateRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: hp(1),
    },
    stateText: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 13,
    },
    infoBox: {
      backgroundColor: colors.cardBg,
      borderRadius: 14,
      padding: wp(4),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      borderLeftWidth: 3,
      borderLeftColor: colors.primary,
      marginBottom: hp(1.5),
      ...cardShadow(isDark),
    },
    infoTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: wp(2),
      marginBottom: hp(0.6),
    },
    infoTitle: {
      color: colors.appText || colors.text,
      fontFamily: fonts.semibold,
      fontSize: 14,
    },
    infoText: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 12,
      lineHeight: 18,
    },
    footer: {
      paddingHorizontal: wp(4),
      paddingTop: hp(1.5),
      paddingBottom: Math.max(hp(2.5), bottomInset + hp(1)),
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.surfaceBorder || colors.border,
      backgroundColor: colors.cardBg,
      gap: 10,
    },
    footerRow: {
      flexDirection: 'row',
      gap: 10,
    },
    primaryBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
      borderRadius: 12,
      paddingVertical: hp(1.7),
      gap: 8,
    },
    primaryBtnText: {
      color: colors.white,
      fontFamily: fonts.semibold,
      fontSize: 14,
      letterSpacing: 0.2,
    },
    secondaryBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 12,
      paddingVertical: hp(1.7),
      gap: 8,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : colors.inputBg,
    },
    secondaryBtnText: {
      color: colors.appText || colors.text,
      fontFamily: fonts.semibold,
      fontSize: 13,
    },
    btnDisabled: {
      opacity: 0.65,
    },
    searchBox: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.cardBg,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      paddingHorizontal: wp(3),
      height: hp(5.2),
      gap: wp(2),
      ...cardShadow(isDark),
    },
    searchInput: {
      flex: 1,
      color: colors.text,
      fontFamily: fonts.regular,
      fontSize: 13,
      paddingVertical: 0,
    },
    toolbar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: hp(1.8),
    },
  }
}
