import { StyleSheet, Platform } from 'react-native'
import { fonts } from '../../../constant'
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from '../../../theme/layout'
import { createSettingsScreenStyles, cardShadow } from '../shared/settingsScreenTheme'

export const getStyles = (colors, isDark = false, options = {}) =>
  StyleSheet.create({
    ...createSettingsScreenStyles(colors, isDark, options),

    mainCard: {
      borderRadius: 18,
      backgroundColor: colors.cardBg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      overflow: 'hidden',
      marginBottom: hp(2),
      ...cardShadow(isDark),
    },
    profileHero: {
      paddingHorizontal: wp(5),
      paddingTop: hp(2.4),
      paddingBottom: hp(2),
      alignItems: 'center',
      overflow: 'hidden',
    },
    heroGradient: {
      ...StyleSheet.absoluteFillObject,
    },
    avatarBorder: {
      width: wp(22),
      height: wp(22),
      borderRadius: wp(11),
      borderWidth: 2.5,
      borderColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: hp(1.4),
      backgroundColor: colors.cardBg,
    },
    avatar: {
      width: wp(19),
      height: wp(19),
      borderRadius: wp(9.5),
      backgroundColor: colors.inputBg,
    },
    orgName: {
      color: colors.appText || colors.text,
      fontFamily: fonts.bold,
      fontSize: 20,
      letterSpacing: 0.2,
      textAlign: 'center',
      paddingHorizontal: wp(2),
    },
    websiteChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: hp(0.8),
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
      backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : colors.inputBg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
    },
    websiteText: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 12,
      maxWidth: wp(70),
    },
    fieldRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingVertical: hp(1.4),
      minHeight: hp(6.8),
    },
    rowDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.surfaceBorder || colors.border,
    },
    iconBox: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: wp(3),
      flexShrink: 0,
      backgroundColor: isDark ? `${colors.primary}18` : `${colors.primary}10`,
    },
    fieldContent: {
      flex: 1,
      justifyContent: 'center',
      minWidth: 0,
      paddingTop: 2,
    },
    fieldLabel: {
      color: colors.gray,
      fontSize: 11,
      fontFamily: fonts.semibold,
      letterSpacing: 0.5,
      marginBottom: 4,
      textTransform: 'uppercase',
    },
    fieldValue: {
      color: colors.appText || colors.text,
      fontFamily: fonts.medium,
      fontSize: 14,
      lineHeight: 20,
    },
    sectionCard: {
      backgroundColor: colors.cardBg,
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      paddingHorizontal: wp(4),
      paddingTop: hp(1.4),
      paddingBottom: hp(0.6),
      marginBottom: hp(1.8),
      ...cardShadow(isDark),
    },
    hoursHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: wp(2.5),
      paddingBottom: hp(1.2),
      marginBottom: hp(0.4),
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.surfaceBorder || colors.border,
    },
    hoursHeaderText: {
      color: colors.appText || colors.text,
      fontFamily: fonts.semibold,
      fontSize: 14,
    },
    hoursRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: hp(1.1),
    },
    hoursRowDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.surfaceBorder || colors.border,
    },
    hoursDay: {
      color: colors.appText || colors.text,
      fontFamily: fonts.medium,
      fontSize: 13,
      flex: 1,
    },
    hoursTime: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 13,
      textAlign: 'right',
      flex: 1,
    },
    hoursClosed: {
      color: colors.gray,
      fontStyle: 'italic',
    },
    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.cardBg,
      borderRadius: 16,
      paddingVertical: hp(5),
      paddingHorizontal: wp(8),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.surfaceBorder || colors.border,
      borderStyle: 'dashed',
      marginTop: hp(1),
    },
    emptyIcon: {
      width: 52,
      height: 52,
      borderRadius: 26,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : colors.inputBg,
      marginBottom: hp(1.4),
    },
    emptyTitle: {
      color: colors.appText || colors.text,
      fontFamily: fonts.semibold,
      fontSize: 15,
      marginBottom: 6,
      textAlign: 'center',
    },
    emptyHint: {
      color: colors.gray,
      fontFamily: fonts.regular,
      fontSize: 13,
      textAlign: 'center',
      lineHeight: 19,
    },
  })

export default getStyles
